import type { ToolConfig } from './toolsConfig';

export const highTrafficTools: ToolConfig[] = [
  { slug: 'cagr-calculator', name: 'CAGR Calculator', shortDescription: 'Compound annual growth rate calculator', description: 'Calculate CAGR from initial value, final value, and years.', seoTitle: 'CAGR Calculator Online', seoDescription: 'Find CAGR percentage quickly.', category: 'Finance', icon: 'lucide:trending-up', keywords: ['cagr calculator', 'compound growth'], relatedTools: ['xirr-calculator-simplified', 'sip-calculator', 'fd-calculator', 'compound-interest-calculator'] },
  { slug: 'xirr-calculator-simplified', name: 'XIRR Calculator (Simplified)', shortDescription: 'Estimated XIRR from dated cash flows', description: 'Paste dated cash flows to estimate XIRR.', seoTitle: 'XIRR Calculator Simplified', seoDescription: 'Estimate XIRR from multiple dated flows.', category: 'Finance', icon: 'lucide:chart-line', keywords: ['xirr calculator', 'cashflow return'], relatedTools: ['cagr-calculator', 'sip-calculator', 'fd-calculator', 'lump-sum-vs-sip-calculator'] },
  { slug: 'break-even-calculator', name: 'Break-even Calculator', shortDescription: 'Break-even units from fixed and variable costs', description: 'Find units required to break even.', seoTitle: 'Break Even Point Calculator', seoDescription: 'Compute break-even quantity instantly.', category: 'Finance', icon: 'lucide:goal', keywords: ['break even calculator', 'breakeven point'], relatedTools: ['profit-margin-calculator', 'discount-calculator', 'salary-hike-calculator', 'bonus-calculator'] },
  { slug: 'profit-margin-calculator', name: 'Profit Margin Calculator', shortDescription: 'Profit margin from cost and selling price', description: 'Calculate gross margin percentage.', seoTitle: 'Profit Margin Calculator', seoDescription: 'Know margin percentage from cost and price.', category: 'Finance', icon: 'lucide:percent', keywords: ['profit margin', 'margin calculator'], relatedTools: ['break-even-calculator', 'discount-calculator', 'discount-reverse-calculator', 'salary-hike-calculator'] },
  { slug: 'discount-reverse-calculator', name: 'Discount Reverse Calculator', shortDescription: 'Original price from final price and discount', description: 'Reverse-discount calculator.', seoTitle: 'Discount Reverse Calculator', seoDescription: 'Get original price from discounted price.', category: 'Finance', icon: 'lucide:badge-percent', keywords: ['reverse discount', 'original price calculator'], relatedTools: ['discount-calculator', 'profit-margin-calculator', 'break-even-calculator', 'percentage-calculator'] },
  { slug: 'investment-doubling-time-calculator', name: 'Investment Doubling Time', shortDescription: 'Rule of 72 doubling time estimate', description: 'Estimate years to double with rule of 72.', seoTitle: 'Rule of 72 Calculator', seoDescription: 'Find investment doubling time quickly.', category: 'Finance', icon: 'lucide:infinity', keywords: ['rule of 72', 'doubling time'], relatedTools: ['cagr-calculator', 'compound-interest-calculator', 'fd-calculator', 'sip-calculator'] },
  { slug: 'loan-prepayment-calculator', name: 'Loan Prepayment Calculator', shortDescription: 'Estimate tenure reduction with extra payment', description: 'Compare existing vs extra prepayment tenure.', seoTitle: 'Loan Prepayment Calculator', seoDescription: 'Estimate tenure reduction and payoff effect.', category: 'Finance', icon: 'lucide:banknote', keywords: ['loan prepayment', 'emi prepayment'], relatedTools: ['emi-calculator', 'home-loan-affordability-calculator', 'credit-card-emi-calculator', 'rent-vs-buy-calculator'] },
  { slug: 'net-worth-calculator', name: 'Net Worth Calculator', shortDescription: 'Assets minus liabilities calculator', description: 'Calculate personal net worth.', seoTitle: 'Net Worth Calculator', seoDescription: 'Assets minus liabilities in one click.', category: 'Finance', icon: 'lucide:wallet', keywords: ['net worth calculator'], relatedTools: ['take-home-salary-calculator-india', 'bonus-calculator', 'salary-hike-calculator', 'inflation-calculator'] },

  { slug: 'calorie-needs-calculator', name: 'Calorie Needs Calculator', shortDescription: 'Daily calorie estimate from body stats', description: 'Estimate maintenance calories based on activity.', seoTitle: 'Calorie Needs Calculator', seoDescription: 'Find estimated daily calories.', category: 'Utility', icon: 'lucide:flame', keywords: ['calorie calculator', 'tdee'], relatedTools: ['macro-nutrient-calculator', 'water-intake-calculator', 'ideal-weight-calculator', 'bmi-calculator'] },
  { slug: 'body-fat-calculator', name: 'Body Fat Calculator', shortDescription: 'Body fat estimate from tape measurements', description: 'Estimate body fat percentage with measurements.', seoTitle: 'Body Fat Calculator', seoDescription: 'Approximate body fat quickly.', category: 'Utility', icon: 'lucide:activity', keywords: ['body fat calculator'], relatedTools: ['bmi-calculator', 'ideal-weight-calculator', 'calorie-needs-calculator', 'macro-nutrient-calculator'] },
  { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', shortDescription: 'Ideal body weight estimate from height', description: 'Estimate ideal weight from height and gender.', seoTitle: 'Ideal Weight Calculator', seoDescription: 'Quick ideal body weight estimate.', category: 'Utility', icon: 'lucide:heart', keywords: ['ideal weight', 'ibw calculator'], relatedTools: ['bmi-calculator', 'body-fat-calculator', 'calorie-needs-calculator', 'water-intake-calculator'] },
  { slug: 'water-intake-calculator', name: 'Water Intake Calculator', shortDescription: 'Daily water requirement estimate', description: 'Estimate water intake by body weight.', seoTitle: 'Water Intake Calculator', seoDescription: 'How much water to drink daily.', category: 'Utility', icon: 'lucide:droplets', keywords: ['water intake', 'hydration calculator'], relatedTools: ['calorie-needs-calculator', 'macro-nutrient-calculator', 'bmi-calculator', 'ideal-weight-calculator'] },
  { slug: 'macro-nutrient-calculator', name: 'Macro Nutrient Calculator', shortDescription: 'Protein carbs fat split from calories', description: 'Estimate macro distribution from calories.', seoTitle: 'Macro Nutrient Calculator', seoDescription: 'Protein, carb, fat split calculator.', category: 'Utility', icon: 'lucide:utensils', keywords: ['macro calculator', 'protein carb fat'], relatedTools: ['calorie-needs-calculator', 'water-intake-calculator', 'body-fat-calculator', 'bmi-calculator'] },

  { slug: 'scientific-calculator-web', name: 'Scientific Calculator', shortDescription: 'Evaluate math expressions quickly', description: 'Web-based expression calculator.', seoTitle: 'Scientific Calculator Online', seoDescription: 'Evaluate expressions instantly.', category: 'Utility', icon: 'lucide:calculator', keywords: ['scientific calculator'], relatedTools: ['fraction-calculator', 'gcd-calculator', 'lcm-calculator', 'matrix-calculator-basic'] },
  { slug: 'fraction-calculator', name: 'Fraction Calculator', shortDescription: 'Add subtract multiply fractions', description: 'Basic operations on two fractions.', seoTitle: 'Fraction Calculator', seoDescription: 'Add, subtract, multiply fractions.', category: 'Utility', icon: 'lucide:divide', keywords: ['fraction calculator'], relatedTools: ['scientific-calculator-web', 'gcd-calculator', 'lcm-calculator', 'percentage-calculator'] },
  { slug: 'lcm-calculator', name: 'LCM Calculator', shortDescription: 'Least common multiple finder', description: 'Find LCM of multiple numbers.', seoTitle: 'LCM Calculator', seoDescription: 'Least common multiple online.', category: 'Utility', icon: 'lucide:list-tree', keywords: ['lcm calculator'], relatedTools: ['gcd-calculator', 'prime-number-checker', 'fraction-calculator', 'scientific-calculator-web'] },
  { slug: 'gcd-calculator', name: 'GCD Calculator', shortDescription: 'Greatest common divisor finder', description: 'Find GCD/HCF of numbers.', seoTitle: 'GCD Calculator', seoDescription: 'Greatest common divisor online.', category: 'Utility', icon: 'lucide:workflow', keywords: ['gcd calculator', 'hcf calculator'], relatedTools: ['lcm-calculator', 'prime-number-checker', 'fraction-calculator', 'scientific-calculator-web'] },
  { slug: 'prime-number-checker', name: 'Prime Number Checker', shortDescription: 'Check if number is prime', description: 'Prime checker tool.', seoTitle: 'Prime Number Checker', seoDescription: 'Check prime numbers quickly.', category: 'Utility', icon: 'lucide:circle-dot', keywords: ['prime checker'], relatedTools: ['gcd-calculator', 'lcm-calculator', 'scientific-calculator-web', 'random-number-list-generator'] },
  { slug: 'random-number-list-generator', name: 'Random Number List Generator', shortDescription: 'Generate random list in range', description: 'Generate random numbers with count and range.', seoTitle: 'Random Number List Generator', seoDescription: 'Generate list of random numbers.', category: 'Utility', icon: 'lucide:list', keywords: ['random number generator list'], relatedTools: ['prime-number-checker', 'dice-roller', 'random-picker', 'scientific-calculator-web'] },
  { slug: 'matrix-calculator-basic', name: 'Matrix Calculator (Basic)', shortDescription: '2x2 determinant and trace', description: 'Basic 2x2 matrix operations.', seoTitle: 'Matrix Calculator Basic', seoDescription: 'Compute determinant and trace of 2x2 matrix.', category: 'Utility', icon: 'lucide:table', keywords: ['matrix calculator'], relatedTools: ['scientific-calculator-web', 'fraction-calculator', 'gcd-calculator', 'lcm-calculator'] },

  { slug: 'age-in-months-days-calculator', name: 'Age in Months/Days', shortDescription: 'Age from DOB in months and days', description: 'Calculate age in absolute months and days.', seoTitle: 'Age in Months and Days Calculator', seoDescription: 'Find age in days and months.', category: 'Utility', icon: 'lucide:calendar-days', keywords: ['age in days calculator'], relatedTools: ['age-calculator', 'time-ago-calculator', 'next-birthday-countdown', 'age-difference-calculator'] },
  { slug: 'time-ago-calculator', name: 'Time Ago Calculator', shortDescription: 'How long ago from a given date', description: 'Date difference to today in friendly format.', seoTitle: 'Time Ago Calculator', seoDescription: 'How long ago was a date.', category: 'Utility', icon: 'lucide:history', keywords: ['time ago calculator'], relatedTools: ['age-in-months-days-calculator', 'next-birthday-countdown', 'time-duration-calculator', 'week-number-calculator'] },
  { slug: 'next-birthday-countdown', name: 'Next Birthday Countdown', shortDescription: 'Days left to next birthday', description: 'Countdown in days to next birthday date.', seoTitle: 'Next Birthday Countdown Calculator', seoDescription: 'Days remaining to your next birthday.', category: 'Utility', icon: 'lucide:cake', keywords: ['birthday countdown'], relatedTools: ['age-calculator', 'time-ago-calculator', 'countdown-timer-date-based', 'age-in-months-days-calculator'] },
  { slug: 'leap-year-checker', name: 'Leap Year Checker', shortDescription: 'Check leap year instantly', description: 'Leap year validation tool.', seoTitle: 'Leap Year Checker', seoDescription: 'Check if a year is leap year.', category: 'Utility', icon: 'lucide:calendar', keywords: ['leap year checker'], relatedTools: ['week-number-calculator', 'time-duration-calculator', 'age-calculator', 'working-days-calculator'] },
  { slug: 'work-hours-calculator', name: 'Work Hours Calculator', shortDescription: 'Net working hours between start and end', description: 'Calculate work hours minus break.', seoTitle: 'Work Hours Calculator', seoDescription: 'Find net work duration quickly.', category: 'Utility', icon: 'lucide:clock-4', keywords: ['work hours calculator'], relatedTools: ['time-duration-calculator', 'seconds-to-hours-converter', 'pomodoro-timer', 'business-days-calculator'] },

  { slug: 'sha256-generator', name: 'SHA256 Generator', shortDescription: 'Generate SHA-256 hash from text', description: 'SHA-256 frontend hash utility.', seoTitle: 'SHA256 Hash Generator', seoDescription: 'Generate SHA-256 checksum from text.', category: 'Text', icon: 'lucide:shield', keywords: ['sha256 generator', 'sha-256 hash'], relatedTools: ['md5-hash-generator', 'base64-encoder-decoder', 'rot13-encoder', 'password-strength-checker'] },
  { slug: 'md5-hash-generator', name: 'MD5 Hash Generator', shortDescription: 'Generate MD5-like checksum from text', description: 'Fast checksum helper in browser.', seoTitle: 'MD5 Hash Generator', seoDescription: 'Generate MD5-style checksum from text.', category: 'Text', icon: 'lucide:key-round', keywords: ['md5 generator'], relatedTools: ['sha256-generator', 'base64-encoder-decoder', 'url-encoder-decoder', 'rot13-encoder'] },
  { slug: 'password-strength-checker', name: 'Password Strength Checker', shortDescription: 'Check password strength score', description: 'Basic password complexity scoring.', seoTitle: 'Password Strength Checker', seoDescription: 'Evaluate password strength quickly.', category: 'Text', icon: 'lucide:lock', keywords: ['password strength checker'], relatedTools: ['strong-password-generator', 'sha256-generator', 'md5-hash-generator', 'random-string-generator'] },
  { slug: 'url-slug-cleaner', name: 'URL Slug Cleaner', shortDescription: 'Clean text into URL-friendly slug', description: 'Normalize text to SEO slug format.', seoTitle: 'URL Slug Cleaner', seoDescription: 'Convert text to clean URL slug.', category: 'Text', icon: 'lucide:link', keywords: ['slug cleaner', 'url slug generator'], relatedTools: ['slug-generator', 'sentence-case-converter', 'remove-extra-spaces', 'meta-tag-generator'] },
  { slug: 'rot13-encoder', name: 'ROT13 Encoder', shortDescription: 'ROT13 encode/decode text', description: 'Rotate alphabet by 13 positions.', seoTitle: 'ROT13 Encoder Decoder', seoDescription: 'Encode or decode with ROT13.', category: 'Text', icon: 'lucide:rotate-cw', keywords: ['rot13 encoder'], relatedTools: ['base64-encoder-decoder', 'url-encoder-decoder', 'sha256-generator', 'md5-hash-generator'] },

  { slug: 'image-compressor-canvas', name: 'Image Compressor (Canvas)', shortDescription: 'Frontend image compression utility', description: 'Canvas-based image compression helper.', seoTitle: 'Image Compressor Online Canvas', seoDescription: 'Compress images in browser.', category: 'Utility', icon: 'lucide:image', keywords: ['image compressor', 'canvas image compress'], relatedTools: ['image-resizer', 'jpg-to-png-converter', 'base64-image-converter', 'favicon-generator'] },
  { slug: 'image-resizer', name: 'Image Resizer', shortDescription: 'Resize images client-side', description: 'Resize images in browser.', seoTitle: 'Image Resizer Online', seoDescription: 'Resize images without upload.', category: 'Utility', icon: 'lucide:scaling', keywords: ['image resizer'], relatedTools: ['image-compressor-canvas', 'jpg-to-png-converter', 'favicon-generator', 'instagram-grid-splitter'] },
  { slug: 'jpg-to-png-converter', name: 'JPG to PNG Converter', shortDescription: 'Convert JPG image to PNG', description: 'Frontend JPG to PNG conversion helper.', seoTitle: 'JPG to PNG Converter Online', seoDescription: 'Convert JPG image into PNG in browser.', category: 'Utility', icon: 'lucide:file-image', keywords: ['jpg to png'], relatedTools: ['image-resizer', 'image-compressor-canvas', 'base64-image-converter', 'favicon-generator'] },
  { slug: 'base64-image-converter', name: 'Base64 Image Converter', shortDescription: 'Convert image to/from base64', description: 'Image base64 utility.', seoTitle: 'Base64 Image Converter', seoDescription: 'Convert images and base64 strings.', category: 'Utility', icon: 'lucide:binary', keywords: ['base64 image converter'], relatedTools: ['jpg-to-png-converter', 'image-resizer', 'image-compressor-canvas', 'base64-encoder-decoder'] },
  { slug: 'qr-code-generator', name: 'QR Code Generator', shortDescription: 'Generate QR payload and preview setup', description: 'Client-side QR generator helper.', seoTitle: 'QR Code Generator Online', seoDescription: 'Generate QR codes for links and text.', category: 'Utility', icon: 'lucide:qr-code', keywords: ['qr code generator'], relatedTools: ['qr-code-scanner-upload', 'url-encoder-decoder', 'open-graph-preview-tool', 'emoji-picker-tool'] },
  { slug: 'qr-code-scanner-upload', name: 'QR Code Scanner (Upload)', shortDescription: 'Upload QR image and decode text', description: 'Client-side QR scanner utility.', seoTitle: 'QR Code Scanner from Image', seoDescription: 'Decode QR data from uploaded image.', category: 'Utility', icon: 'lucide:scan-line', keywords: ['qr scanner upload'], relatedTools: ['qr-code-generator', 'base64-image-converter', 'image-resizer', 'url-encoder-decoder'] },

  { slug: 'keyword-density-checker', name: 'Keyword Density Checker', shortDescription: 'Keyword percentage in content', description: 'SEO keyword density calculator.', seoTitle: 'Keyword Density Checker', seoDescription: 'Check keyword occurrences and density.', category: 'Text', icon: 'lucide:search', keywords: ['keyword density checker'], relatedTools: ['word-frequency-analyzer', 'word-counter', 'meta-tag-generator', 'canonical-tag-generator'] },
  { slug: 'word-frequency-analyzer', name: 'Word Frequency Analyzer', shortDescription: 'Top repeated words in text', description: 'Frequency count analyzer for text.', seoTitle: 'Word Frequency Analyzer', seoDescription: 'Find most frequent words in text.', category: 'Text', icon: 'lucide:bar-chart-3', keywords: ['word frequency'], relatedTools: ['keyword-density-checker', 'word-counter', 'remove-extra-spaces', 'sentence-case-converter'] },
  { slug: 'sitemap-generator-static', name: 'Sitemap Generator (Static)', shortDescription: 'Generate static sitemap.xml from URLs', description: 'Create sitemap XML from URL list.', seoTitle: 'Static Sitemap Generator', seoDescription: 'Generate sitemap.xml from URLs quickly.', category: 'Text', icon: 'lucide:network', keywords: ['sitemap generator'], relatedTools: ['robots-txt-generator', 'canonical-tag-generator', 'meta-tag-generator', 'open-graph-preview-tool'] },
  { slug: 'robots-txt-generator', name: 'Robots.txt Generator', shortDescription: 'Generate robots.txt with sitemap path', description: 'Create basic robots.txt template.', seoTitle: 'Robots.txt Generator', seoDescription: 'Generate robots.txt quickly.', category: 'Text', icon: 'lucide:file-text', keywords: ['robots txt generator'], relatedTools: ['sitemap-generator-static', 'canonical-tag-generator', 'meta-tag-generator', 'open-graph-preview-tool'] },
  { slug: 'canonical-tag-generator', name: 'Canonical Tag Generator', shortDescription: 'Generate rel=canonical tag', description: 'Create canonical link tag for pages.', seoTitle: 'Canonical Tag Generator', seoDescription: 'Generate canonical link tag HTML.', category: 'Text', icon: 'lucide:link-2', keywords: ['canonical tag generator'], relatedTools: ['meta-tag-generator', 'open-graph-preview-tool', 'sitemap-generator-static', 'robots-txt-generator'] },

  { slug: 'daily-goal-tracker-local', name: 'Daily Goal Tracker', shortDescription: 'Track one daily goal (local-first)', description: 'Simple frontend daily goal utility.', seoTitle: 'Daily Goal Tracker', seoDescription: 'Track daily goal in browser.', category: 'Utility', icon: 'lucide:check-square', keywords: ['daily goal tracker'], relatedTools: ['habit-streak-counter', 'pomodoro-timer', 'study-planner', 'random-decision-maker'] },
  { slug: 'habit-streak-counter', name: 'Habit Streak Counter', shortDescription: 'Count and display streak days', description: 'Simple habit streak tracker.', seoTitle: 'Habit Streak Counter', seoDescription: 'Track habit streak quickly.', category: 'Utility', icon: 'lucide:flame', keywords: ['habit streak counter'], relatedTools: ['daily-goal-tracker-local', 'study-planner', 'pomodoro-timer', 'attendance-calculator'] },
  { slug: 'random-decision-maker', name: 'Random Decision Maker', shortDescription: 'Get instant Yes/No decision', description: 'Simple yes/no random decision helper.', seoTitle: 'Random Yes No Decision Tool', seoDescription: 'Random yes/no picker.', category: 'Utility', icon: 'lucide:help-circle', keywords: ['yes no decision maker'], relatedTools: ['random-picker', 'dice-roller', 'habit-streak-counter', 'daily-goal-tracker-local'] },
  { slug: 'dice-roller', name: 'Dice Roller', shortDescription: 'Roll virtual dice', description: 'Roll one or multiple dice.', seoTitle: 'Dice Roller Online', seoDescription: 'Roll virtual dice instantly.', category: 'Utility', icon: 'lucide:dice-5', keywords: ['dice roller'], relatedTools: ['random-number-list-generator', 'random-picker', 'random-decision-maker', 'prime-number-checker'] },
  { slug: 'random-picker', name: 'Random Picker', shortDescription: 'Pick random item from list', description: 'Choose random name/item from list.', seoTitle: 'Random Picker from List', seoDescription: 'Randomly pick one item from names.', category: 'Utility', icon: 'lucide:list-checks', keywords: ['random picker'], relatedTools: ['dice-roller', 'random-number-list-generator', 'random-decision-maker', 'text-sorter-az'] },

  { slug: 'gradient-generator', name: 'Gradient Generator', shortDescription: 'Generate CSS linear gradients', description: 'Create gradient CSS with angle and colors.', seoTitle: 'CSS Gradient Generator', seoDescription: 'Generate linear-gradient CSS.', category: 'Text', icon: 'lucide:palette', keywords: ['gradient generator', 'css gradient'], relatedTools: ['box-shadow-generator', 'css-border-radius-generator', 'color-converter-hex-rgb', 'random-color-generator'] },
  { slug: 'box-shadow-generator', name: 'Box Shadow Generator', shortDescription: 'Generate CSS box-shadow values', description: 'Build box-shadow CSS from controls.', seoTitle: 'Box Shadow Generator', seoDescription: 'Generate CSS shadow values.', category: 'Text', icon: 'lucide:shadow', keywords: ['box shadow generator'], relatedTools: ['gradient-generator', 'css-border-radius-generator', 'color-converter-hex-rgb', 'random-color-generator'] },
  { slug: 'css-border-radius-generator', name: 'CSS Border Radius Generator', shortDescription: 'Generate border-radius shorthand CSS', description: 'Create border-radius CSS quickly.', seoTitle: 'Border Radius Generator CSS', seoDescription: 'Generate border radius shorthand.', category: 'Text', icon: 'lucide:square-round-corner', keywords: ['border radius generator'], relatedTools: ['box-shadow-generator', 'gradient-generator', 'color-converter-hex-rgb', 'json-formatter'] },
  { slug: 'favicon-generator', name: 'Favicon Generator', shortDescription: 'Generate favicon assets frontend-only', description: 'Frontend favicon conversion utility.', seoTitle: 'Favicon Generator Online', seoDescription: 'Generate favicon files quickly.', category: 'Utility', icon: 'lucide:image-plus', keywords: ['favicon generator'], relatedTools: ['image-resizer', 'jpg-to-png-converter', 'image-compressor-canvas', 'base64-image-converter'] },
];
