import type { ToolConfig } from './toolsConfig';

export const studentTools: ToolConfig[] = [
  { slug: 'algebra-equation-solver', name: 'Algebra Equation Solver', shortDescription: 'Solve ax+b=c with steps', description: 'Linear algebra equation solver with steps.', seoTitle: 'Algebra Equation Solver with Steps', seoDescription: 'Solve linear equations like ax+b=c.', category: 'Utility', icon: 'lucide:sigma', keywords: ['algebra solver', 'linear equation solver'], relatedTools: ['quadratic-equation-solver-steps', 'scientific-calculator-web', 'ratio-simplifier', 'fraction-simplifier'] },
  { slug: 'quadratic-equation-solver-steps', name: 'Quadratic Equation Solver', shortDescription: 'Find roots with step-by-step formula', description: 'Quadratic roots and discriminant explanation.', seoTitle: 'Quadratic Equation Solver with Steps', seoDescription: 'Solve ax²+bx+c and get roots.', category: 'Utility', icon: 'lucide:function-square', keywords: ['quadratic solver', 'roots calculator'], relatedTools: ['algebra-equation-solver', 'power-calculator', 'square-root-calculator-steps', 'scientific-calculator-web'] },
  { slug: 'percentage-word-problem-solver', name: 'Percentage Word Problem Solver', shortDescription: 'Part-whole percentage with explanation', description: 'Solve percentage-type word problems from values.', seoTitle: 'Percentage Word Problem Solver', seoDescription: 'Get percentage answer and explanation.', category: 'Utility', icon: 'lucide:message-circle-question', keywords: ['percentage problem solver'], relatedTools: ['percentage-calculator', 'ratio-simplifier', 'marks-percentage-calculator', 'exam-score-predictor'] },
  { slug: 'ratio-simplifier', name: 'Ratio Simplifier', shortDescription: 'Reduce ratios to simplest form', description: 'Simplify ratio a:b using HCF.', seoTitle: 'Ratio Simplifier Online', seoDescription: 'Simplify ratio instantly.', category: 'Utility', icon: 'lucide:scaling', keywords: ['ratio simplifier'], relatedTools: ['fraction-simplifier', 'gcd-calculator', 'lcm-calculator', 'percentage-word-problem-solver'] },
  { slug: 'fraction-simplifier', name: 'Fraction Simplifier', shortDescription: 'Reduce fractions quickly', description: 'Simplify numerator/denominator to lowest terms.', seoTitle: 'Fraction Simplifier', seoDescription: 'Reduce fractions in one click.', category: 'Utility', icon: 'lucide:divide', keywords: ['fraction simplifier'], relatedTools: ['fraction-to-decimal-converter', 'decimal-to-fraction-converter', 'ratio-simplifier', 'fraction-calculator'] },
  { slug: 'fraction-to-decimal-converter', name: 'Fraction to Decimal Converter', shortDescription: 'Convert a/b to decimal', description: 'Fraction to decimal conversion tool.', seoTitle: 'Fraction to Decimal Converter', seoDescription: 'Convert fractions to decimals.', category: 'Utility', icon: 'lucide:arrow-right-left', keywords: ['fraction to decimal'], relatedTools: ['decimal-to-fraction-converter', 'fraction-simplifier', 'fraction-calculator', 'scientific-calculator-web'] },
  { slug: 'decimal-to-fraction-converter', name: 'Decimal to Fraction Converter', shortDescription: 'Convert decimal to fraction', description: 'Convert decimal values into simplified fraction.', seoTitle: 'Decimal to Fraction Converter', seoDescription: 'Convert decimal to reduced fraction.', category: 'Utility', icon: 'lucide:arrow-right-left', keywords: ['decimal to fraction'], relatedTools: ['fraction-to-decimal-converter', 'fraction-simplifier', 'fraction-calculator', 'ratio-simplifier'] },
  { slug: 'square-root-calculator-steps', name: 'Square Root Calculator (with steps)', shortDescription: 'Compute √x with simple steps', description: 'Square root calculator with concept step.', seoTitle: 'Square Root Calculator with Steps', seoDescription: 'Find square roots and explanation.', category: 'Utility', icon: 'lucide:radical', keywords: ['square root calculator'], relatedTools: ['cube-root-calculator', 'power-calculator', 'quadratic-equation-solver-steps', 'scientific-calculator-web'] },
  { slug: 'cube-root-calculator', name: 'Cube Root Calculator', shortDescription: 'Compute ∛x quickly', description: 'Cube root calculator for any number.', seoTitle: 'Cube Root Calculator', seoDescription: 'Find cube root instantly.', category: 'Utility', icon: 'lucide:box', keywords: ['cube root calculator'], relatedTools: ['square-root-calculator-steps', 'power-calculator', 'scientific-calculator-web', 'prime-number-checker'] },
  { slug: 'power-calculator', name: 'Power Calculator (x^y)', shortDescription: 'Evaluate x raised to y', description: 'Exponent calculator.', seoTitle: 'Power Calculator x^y', seoDescription: 'Compute powers quickly.', category: 'Utility', icon: 'lucide:superscript', keywords: ['power calculator'], relatedTools: ['square-root-calculator-steps', 'cube-root-calculator', 'scientific-calculator-web', 'quadratic-equation-solver-steps'] },

  { slug: 'triangle-solver-basic', name: 'Triangle Solver', shortDescription: 'Perimeter and area from 3 sides', description: 'Basic triangle solution from side lengths.', seoTitle: 'Triangle Solver Basic', seoDescription: 'Solve triangle perimeter and area.', category: 'Utility', icon: 'lucide:triangle', keywords: ['triangle solver'], relatedTools: ['pythagorean-theorem-solver', 'area-calculator-multi-shapes', 'circle-calculator', 'volume-calculator-3d-shapes'] },
  { slug: 'circle-calculator', name: 'Circle Calculator', shortDescription: 'Area and circumference from radius', description: 'Circle formulas in one place.', seoTitle: 'Circle Calculator Area Circumference', seoDescription: 'Calculate area and circumference.', category: 'Utility', icon: 'lucide:circle', keywords: ['circle calculator'], relatedTools: ['area-calculator-multi-shapes', 'angle-converter-deg-rad', 'triangle-solver-basic', 'volume-calculator-3d-shapes'] },
  { slug: 'area-calculator-multi-shapes', name: 'Area Calculator (Multi Shapes)', shortDescription: 'Rectangle triangle circle area', description: 'Area formulas for key shapes.', seoTitle: 'Area Calculator Multiple Shapes', seoDescription: 'Find area for common shapes.', category: 'Utility', icon: 'lucide:shapes', keywords: ['area calculator'], relatedTools: ['circle-calculator', 'triangle-solver-basic', 'volume-calculator-3d-shapes', 'pythagorean-theorem-solver'] },
  { slug: 'volume-calculator-3d-shapes', name: 'Volume Calculator (3D Shapes)', shortDescription: 'Cuboid cylinder sphere volume', description: 'Volume formulas for common solids.', seoTitle: 'Volume Calculator 3D Shapes', seoDescription: 'Calculate volume of 3D shapes.', category: 'Utility', icon: 'lucide:cuboid', keywords: ['volume calculator'], relatedTools: ['area-calculator-multi-shapes', 'circle-calculator', 'triangle-solver-basic', 'pythagorean-theorem-solver'] },
  { slug: 'pythagorean-theorem-solver', name: 'Pythagorean Theorem Solver', shortDescription: 'Find hypotenuse with steps', description: 'Use c²=a²+b² for right triangles.', seoTitle: 'Pythagorean Theorem Solver', seoDescription: 'Find hypotenuse and steps.', category: 'Utility', icon: 'lucide:triangle-right', keywords: ['pythagorean theorem solver'], relatedTools: ['triangle-solver-basic', 'square-root-calculator-steps', 'area-calculator-multi-shapes', 'scientific-calculator-web'] },
  { slug: 'angle-converter-deg-rad', name: 'Angle Converter (deg ↔ rad)', shortDescription: 'Convert degrees to radians', description: 'Angle unit converter.', seoTitle: 'Degree to Radian Converter', seoDescription: 'Convert angles between degrees and radians.', category: 'Utility', icon: 'lucide:rotate-3d', keywords: ['degree to radian converter'], relatedTools: ['circle-calculator', 'scientific-calculator-web', 'triangle-solver-basic', 'pythagorean-theorem-solver'] },

  { slug: 'multiplication-table-generator', name: 'Multiplication Table Generator', shortDescription: 'Generate table of any number', description: 'Times table generator for practice.', seoTitle: 'Multiplication Table Generator', seoDescription: 'Generate multiplication table quickly.', category: 'Utility', icon: 'lucide:grid-2x2', keywords: ['multiplication table'], relatedTools: ['mental-math-trainer', 'math-flashcards-generator', 'random-math-quiz-generator', 'arithmetic-sequence-calculator'] },
  { slug: 'random-math-quiz-generator', name: 'Random Math Quiz Generator', shortDescription: 'Generate random practice questions', description: 'Math quiz generator for students.', seoTitle: 'Random Math Quiz Generator', seoDescription: 'Practice random math questions.', category: 'Utility', icon: 'lucide:brain', keywords: ['math quiz generator'], relatedTools: ['mental-math-trainer', 'math-flashcards-generator', 'multiplication-table-generator', 'scientific-calculator-web'] },
  { slug: 'mental-math-trainer', name: 'Mental Math Trainer', shortDescription: 'Quick arithmetic question trainer', description: 'Train mental calculations with random prompts.', seoTitle: 'Mental Math Trainer', seoDescription: 'Practice quick mental math.', category: 'Utility', icon: 'lucide:zap', keywords: ['mental math trainer'], relatedTools: ['random-math-quiz-generator', 'multiplication-table-generator', 'math-flashcards-generator', 'random-number-list-generator'] },
  { slug: 'math-flashcards-generator', name: 'Math Flashcards Generator', shortDescription: 'Generate flashcards for arithmetic', description: 'Flashcard practice prompts.', seoTitle: 'Math Flashcards Generator', seoDescription: 'Generate math flashcards.', category: 'Utility', icon: 'lucide:book-open', keywords: ['math flashcards'], relatedTools: ['multiplication-table-generator', 'mental-math-trainer', 'random-math-quiz-generator', 'fraction-calculator'] },
  { slug: 'arithmetic-sequence-calculator', name: 'Arithmetic Sequence Calculator', shortDescription: 'n-th term and sum of AP', description: 'Arithmetic progression calculator.', seoTitle: 'Arithmetic Sequence Calculator', seoDescription: 'Find AP terms and sums.', category: 'Utility', icon: 'lucide:list', keywords: ['arithmetic progression calculator'], relatedTools: ['geometric-sequence-calculator', 'scientific-calculator-web', 'power-calculator', 'percentage-calculator'] },
  { slug: 'geometric-sequence-calculator', name: 'Geometric Sequence Calculator', shortDescription: 'n-th term and sum of GP', description: 'Geometric progression calculator.', seoTitle: 'Geometric Sequence Calculator', seoDescription: 'Find GP terms and sums.', category: 'Utility', icon: 'lucide:git-branch', keywords: ['geometric progression calculator'], relatedTools: ['arithmetic-sequence-calculator', 'power-calculator', 'scientific-calculator-web', 'compound-interest-calculator'] },

  { slug: 'formula-sheet-generator-classwise', name: 'Formula Sheet Generator', shortDescription: 'Class-wise quick formula sheet', description: 'Generate compact formula list by class.', seoTitle: 'Formula Sheet Generator Class Wise', seoDescription: 'Get important formulas by class.', category: 'Utility', icon: 'lucide:notebook-pen', keywords: ['formula sheet'], relatedTools: ['study-planner', 'random-math-quiz-generator', 'arithmetic-sequence-calculator', 'geometric-sequence-calculator'] },
  { slug: 'marks-to-grade-converter', name: 'Marks to Grade Converter', shortDescription: 'Convert percentage to grade', description: 'Estimate grade from percentage.', seoTitle: 'Marks to Grade Converter', seoDescription: 'Convert marks percentage to grade.', category: 'Utility', icon: 'lucide:badge-check', keywords: ['marks to grade'], relatedTools: ['grade-to-percentage-converter', 'exam-score-predictor', 'marks-percentage-calculator', 'percentage-calculator'] },
  { slug: 'grade-to-percentage-converter', name: 'Grade to Percentage Converter', shortDescription: 'Estimate % range from grade', description: 'Grade-to-percentage range converter.', seoTitle: 'Grade to Percentage Converter', seoDescription: 'Estimate percentage from grade.', category: 'Utility', icon: 'lucide:badge-plus', keywords: ['grade to percentage'], relatedTools: ['marks-to-grade-converter', 'marks-needed-calculator', 'exam-score-predictor', 'marks-percentage-calculator'] },
  { slug: 'exam-score-predictor', name: 'Exam Score Predictor', shortDescription: 'Predict exam score from current trend', description: 'Simple score predictor.', seoTitle: 'Exam Score Predictor', seoDescription: 'Predict expected exam score.', category: 'Utility', icon: 'lucide:target', keywords: ['exam score predictor'], relatedTools: ['marks-to-grade-converter', 'study-time-calculator', 'marks-needed-calculator', 'attendance-calculator'] },
  { slug: 'study-time-calculator', name: 'Study Time Calculator', shortDescription: 'Plan hours per subject before exam', description: 'Calculate study hours and per-subject split.', seoTitle: 'Study Time Calculator', seoDescription: 'Plan study time for exams.', category: 'Utility', icon: 'lucide:timer', keywords: ['study time calculator'], relatedTools: ['study-planner', 'exam-score-predictor', 'pomodoro-timer', 'attendance-calculator'] },

  { slug: 'grammar-checker-basic-rules', name: 'Grammar Checker (Basic)', shortDescription: 'Catch common grammar mistakes', description: 'Basic grammar pattern checker.', seoTitle: 'Basic Grammar Checker', seoDescription: 'Check simple grammar mistakes.', category: 'Text', icon: 'lucide:spell-check', keywords: ['grammar checker basic'], relatedTools: ['sentence-rewriter-simple', 'sentence-shortener-tool', 'sentence-expander-tool', 'word-counter'] },
  { slug: 'sentence-rewriter-simple', name: 'Sentence Rewriter', shortDescription: 'Rewrite sentence with simpler wording', description: 'Simple sentence rewriting logic.', seoTitle: 'Sentence Rewriter Tool', seoDescription: 'Rewrite sentence in simpler form.', category: 'Text', icon: 'lucide:refresh-cw', keywords: ['sentence rewriter'], relatedTools: ['grammar-checker-basic-rules', 'sentence-shortener-tool', 'sentence-expander-tool', 'summary-generator-basic'] },
  { slug: 'passive-to-active-converter', name: 'Passive to Active Voice Converter', shortDescription: 'Convert passive to active (basic)', description: 'Basic passive-to-active voice helper.', seoTitle: 'Passive to Active Voice Converter', seoDescription: 'Convert passive voice to active voice.', category: 'Text', icon: 'lucide:repeat', keywords: ['passive to active'], relatedTools: ['active-to-passive-converter', 'sentence-rewriter-simple', 'grammar-checker-basic-rules', 'summary-generator-basic'] },
  { slug: 'active-to-passive-converter', name: 'Active to Passive Converter', shortDescription: 'Convert active to passive (basic)', description: 'Basic active-to-passive voice helper.', seoTitle: 'Active to Passive Voice Converter', seoDescription: 'Convert active voice to passive.', category: 'Text', icon: 'lucide:repeat-2', keywords: ['active to passive'], relatedTools: ['passive-to-active-converter', 'sentence-rewriter-simple', 'grammar-checker-basic-rules', 'sentence-shortener-tool'] },
  { slug: 'sentence-expander-tool', name: 'Sentence Expander Tool', shortDescription: 'Expand short sentence with detail', description: 'Add supporting details to short sentence.', seoTitle: 'Sentence Expander Tool', seoDescription: 'Expand sentence for writing practice.', category: 'Text', icon: 'lucide:expand', keywords: ['sentence expander'], relatedTools: ['sentence-shortener-tool', 'sentence-rewriter-simple', 'paragraph-generator-structured', 'speech-draft-generator'] },
  { slug: 'sentence-shortener-tool', name: 'Sentence Shortener Tool', shortDescription: 'Shorten long sentence clearly', description: 'Compress long sentence to concise version.', seoTitle: 'Sentence Shortener Tool', seoDescription: 'Shorten long sentence quickly.', category: 'Text', icon: 'lucide:shrink', keywords: ['sentence shortener'], relatedTools: ['sentence-expander-tool', 'sentence-rewriter-simple', 'summary-generator-basic', 'grammar-checker-basic-rules'] },

  { slug: 'synonym-finder-basic', name: 'Synonym Finder', shortDescription: 'Find basic synonyms from static set', description: 'Static synonym lookup.', seoTitle: 'Synonym Finder Basic', seoDescription: 'Find synonyms for common words.', category: 'Text', icon: 'lucide:book-text', keywords: ['synonym finder'], relatedTools: ['antonym-finder-basic', 'word-definition-lookup-static', 'vocabulary-quiz-generator', 'word-of-the-day-generator'] },
  { slug: 'antonym-finder-basic', name: 'Antonym Finder', shortDescription: 'Find opposite words from static set', description: 'Static antonym lookup.', seoTitle: 'Antonym Finder Basic', seoDescription: 'Find antonyms for common words.', category: 'Text', icon: 'lucide:book-minus', keywords: ['antonym finder'], relatedTools: ['synonym-finder-basic', 'word-definition-lookup-static', 'vocabulary-quiz-generator', 'word-of-the-day-generator'] },
  { slug: 'word-definition-lookup-static', name: 'Word Definition Lookup', shortDescription: 'Lookup definitions from static dataset', description: 'Static word definition helper.', seoTitle: 'Word Definition Lookup Tool', seoDescription: 'Find definitions from mini dictionary.', category: 'Text', icon: 'lucide:library', keywords: ['word definition lookup'], relatedTools: ['synonym-finder-basic', 'antonym-finder-basic', 'word-of-the-day-generator', 'vocabulary-quiz-generator'] },
  { slug: 'word-of-the-day-generator', name: 'Word of the Day Generator', shortDescription: 'Daily vocabulary word and meaning', description: 'Random word-of-day tool.', seoTitle: 'Word of the Day Generator', seoDescription: 'Get daily vocabulary word.', category: 'Text', icon: 'lucide:sun', keywords: ['word of the day'], relatedTools: ['vocabulary-quiz-generator', 'word-definition-lookup-static', 'synonym-finder-basic', 'antonym-finder-basic'] },
  { slug: 'vocabulary-quiz-generator', name: 'Vocabulary Quiz Generator', shortDescription: 'Generate quick vocabulary quiz', description: 'Vocabulary MCQ practice generator.', seoTitle: 'Vocabulary Quiz Generator', seoDescription: 'Practice vocabulary with quizzes.', category: 'Text', icon: 'lucide:help-circle', keywords: ['vocabulary quiz'], relatedTools: ['word-of-the-day-generator', 'synonym-finder-basic', 'antonym-finder-basic', 'word-definition-lookup-static'] },

  { slug: 'essay-topic-generator', name: 'Essay Topic Generator', shortDescription: 'Generate essay topics for students', description: 'Essay topic idea generator.', seoTitle: 'Essay Topic Generator for Students', seoDescription: 'Get essay topics quickly.', category: 'Text', icon: 'lucide:file-pen-line', keywords: ['essay topic generator'], relatedTools: ['paragraph-generator-structured', 'story-starter-generator', 'speech-draft-generator', 'letter-format-generator'] },
  { slug: 'paragraph-generator-structured', name: 'Paragraph Generator', shortDescription: 'Generate structured paragraph draft', description: 'Simple paragraph structure generator.', seoTitle: 'Structured Paragraph Generator', seoDescription: 'Generate paragraph draft from topic.', category: 'Text', icon: 'lucide:pilcrow', keywords: ['paragraph generator'], relatedTools: ['essay-topic-generator', 'story-starter-generator', 'speech-draft-generator', 'summary-generator-basic'] },
  { slug: 'story-starter-generator', name: 'Story Starter Generator', shortDescription: 'Generate creative story opening lines', description: 'Story prompt starter generator.', seoTitle: 'Story Starter Generator', seoDescription: 'Generate opening lines for stories.', category: 'Text', icon: 'lucide:book-open-check', keywords: ['story starter generator'], relatedTools: ['essay-topic-generator', 'paragraph-generator-structured', 'speech-draft-generator', 'word-scramble-generator'] },
  { slug: 'letter-format-generator', name: 'Letter Format Generator', shortDescription: 'Formal/informal letter templates', description: 'Letter writing format helper.', seoTitle: 'Letter Format Generator', seoDescription: 'Generate formal and informal letter format.', category: 'Text', icon: 'lucide:mail', keywords: ['letter format generator'], relatedTools: ['speech-draft-generator', 'essay-topic-generator', 'paragraph-generator-structured', 'grammar-checker-basic-rules'] },
  { slug: 'speech-draft-generator', name: 'Speech Draft Generator', shortDescription: 'Generate simple speech draft', description: 'Speech outline and draft helper.', seoTitle: 'Speech Draft Generator', seoDescription: 'Generate speech draft from topic.', category: 'Text', icon: 'lucide:mic', keywords: ['speech draft generator'], relatedTools: ['letter-format-generator', 'essay-topic-generator', 'paragraph-generator-structured', 'story-starter-generator'] },

  { slug: 'reading-time-calculator-student', name: 'Reading Time Calculator', shortDescription: 'Estimate reading time from text', description: 'Reading time and word count tool.', seoTitle: 'Reading Time Calculator Student', seoDescription: 'Estimate reading time in minutes.', category: 'Text', icon: 'lucide:clock-3', keywords: ['reading time calculator'], relatedTools: ['word-counter', 'summary-generator-basic', 'text-complexity-analyzer', 'keyword-extractor-simple'] },
  { slug: 'text-complexity-analyzer', name: 'Text Complexity Analyzer', shortDescription: 'Estimate text complexity level', description: 'Average sentence length complexity score.', seoTitle: 'Text Complexity Analyzer', seoDescription: 'Analyze simple text complexity.', category: 'Text', icon: 'lucide:bar-chart', keywords: ['text complexity analyzer'], relatedTools: ['reading-time-calculator-student', 'summary-generator-basic', 'grammar-checker-basic-rules', 'keyword-extractor-simple'] },
  { slug: 'keyword-extractor-simple', name: 'Keyword Extractor', shortDescription: 'Extract top keywords from text', description: 'Simple keyword extractor with stopword filtering.', seoTitle: 'Keyword Extractor Simple', seoDescription: 'Extract top keywords from paragraph.', category: 'Text', icon: 'lucide:key', keywords: ['keyword extractor'], relatedTools: ['keyword-density-checker', 'word-frequency-analyzer', 'summary-generator-basic', 'text-complexity-analyzer'] },
  { slug: 'summary-generator-basic', name: 'Summary Generator (Basic)', shortDescription: 'Generate short summary from text', description: 'Simple sentence-based summary.', seoTitle: 'Basic Summary Generator', seoDescription: 'Generate short text summary.', category: 'Text', icon: 'lucide:scroll-text', keywords: ['summary generator basic'], relatedTools: ['reading-time-calculator-student', 'text-complexity-analyzer', 'keyword-extractor-simple', 'sentence-shortener-tool'] },

  { slug: 'word-scramble-generator', name: 'Word Scramble Generator', shortDescription: 'Scramble words for fun practice', description: 'Word scramble game generator.', seoTitle: 'Word Scramble Generator', seoDescription: 'Generate scrambled words.', category: 'Text', icon: 'lucide:shuffle', keywords: ['word scramble generator'], relatedTools: ['fill-in-the-blanks-generator', 'vocabulary-quiz-generator', 'story-starter-generator', 'synonym-finder-basic'] },
  { slug: 'crossword-generator-basic-grid', name: 'Crossword Generator (Basic)', shortDescription: 'Generate basic crossword word bank', description: 'Simple crossword helper with word list.', seoTitle: 'Crossword Generator Basic', seoDescription: 'Create basic crossword words list.', category: 'Text', icon: 'lucide:grid-3x3', keywords: ['crossword generator'], relatedTools: ['word-scramble-generator', 'vocabulary-quiz-generator', 'synonym-finder-basic', 'antonym-finder-basic'] },
  { slug: 'fill-in-the-blanks-generator', name: 'Fill-in-the-Blanks Generator', shortDescription: 'Generate blanks from sentence', description: 'Create fill-in-the-blank practice line.', seoTitle: 'Fill in the Blanks Generator', seoDescription: 'Generate fill in the blanks from text.', category: 'Text', icon: 'lucide:pen-square', keywords: ['fill in the blanks generator'], relatedTools: ['word-scramble-generator', 'crossword-generator-basic-grid', 'vocabulary-quiz-generator', 'grammar-checker-basic-rules'] },
];
