import { highTrafficTools } from './highTrafficToolsConfig';
import { studentTools } from './studentToolsConfig';
import { aiContentTools } from './aiToolsConfig';

export type ToolCategory = 'Finance' | 'Utility' | 'Text';

export interface ToolConfig {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  seoTitle: string;
  seoDescription: string;
  category: ToolCategory;
  icon: string;
  keywords: string[];
  relatedTools: string[];
  fullWidth?: boolean;
  /** No tool page header or footer (SEO still in metadata and JSON-LD) */
  immersive?: boolean;
}

/** These paths hide global Navbar, Footer, and the tool layout header/SEO block */
export const TOOL_PATHS_CHROMELESS: readonly string[] = [
  '/tools/fullscreen-stopwatch',
  '/tools/fullscreen-countdown-timer',
];

export const tools: ToolConfig[] = [
  {
    slug: 'sip-calculator',
    name: 'SIP Calculator',
    shortDescription: 'Calculate returns on your systematic investment plan',
    description:
      'Free online SIP Calculator to estimate mutual fund returns. Calculate maturity amount, total investment, and estimated returns for systematic investment plans instantly.',
    seoTitle: 'Free SIP Calculator — Estimate Mutual Fund Returns Online',
    seoDescription:
      'Use our free SIP Calculator to estimate mutual fund returns. Enter monthly investment, expected return rate & tenure to calculate maturity amount instantly. No sign-up needed.',
    category: 'Finance',
    icon: 'lucide:trending-up',
    keywords: [
      'sip calculator',
      'sip return calculator',
      'mutual fund sip calculator',
      'systematic investment plan calculator',
      'sip maturity calculator',
      'monthly sip calculator',
      'sip calculator india',
      'online sip calculator',
      'sip investment calculator',
      'sip calculator with graph',
    ],
    relatedTools: ['emi-calculator', 'fd-calculator', 'percentage-calculator', 'discount-calculator'],
  },
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    shortDescription: 'Calculate monthly EMI for home, car, or personal loans',
    description:
      'Free EMI Calculator to calculate equated monthly installments for any loan. Know your monthly payment, total interest, and total repayment amount instantly.',
    seoTitle: 'EMI Calculator — Home, Car & Personal Loan EMI Calculator',
    seoDescription:
      'Free EMI Calculator for home loan, car loan & personal loan. Enter loan amount, interest rate & tenure to calculate monthly EMI, total interest & total repayment instantly.',
    category: 'Finance',
    icon: 'lucide:landmark',
    keywords: [
      'emi calculator',
      'loan emi calculator',
      'home loan emi calculator',
      'car loan emi calculator',
      'personal loan emi calculator',
      'bank loan emi calculator',
      'emi calculator india',
      'monthly emi calculator',
      'housing loan emi calculator',
      'emi calculation formula',
    ],
    relatedTools: ['sip-calculator', 'fd-calculator', 'gst-calculator', 'percentage-calculator'],
  },
  {
    slug: 'fd-calculator',
    name: 'FD Calculator',
    shortDescription: 'Calculate fixed deposit maturity amount and interest',
    description:
      'Free Fixed Deposit (FD) Calculator to compute maturity amount and interest earned. Compare returns for different compounding frequencies and tenures.',
    seoTitle: 'FD Calculator — Fixed Deposit Maturity & Interest Calculator',
    seoDescription:
      'Free FD Calculator to calculate fixed deposit maturity amount & interest earned. Compare returns across compounding frequencies & tenures. Works for SBI, HDFC & all banks.',
    category: 'Finance',
    icon: 'lucide:piggy-bank',
    keywords: [
      'fd calculator',
      'fixed deposit calculator',
      'fd maturity calculator',
      'fd interest calculator',
      'bank fd calculator',
      'fd calculator online',
      'fd return calculator',
      'fd calculator india',
      'sbi fd calculator',
      'fd calculator with interest rate',
    ],
    relatedTools: ['sip-calculator', 'emi-calculator', 'percentage-calculator', 'discount-calculator'],
  },
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    shortDescription: 'Calculate GST amount for any product or service',
    description:
      'Free online GST Calculator to compute GST amount for 5%, 12%, 18%, and 28% slabs. Calculate both GST-exclusive and GST-inclusive amounts instantly.',
    seoTitle: 'GST Calculator — Calculate GST Online (5%, 12%, 18%, 28%)',
    seoDescription:
      'Free GST Calculator for all tax slabs — 5%, 12%, 18% & 28%. Calculate GST-exclusive & GST-inclusive amounts with CGST, SGST & IGST breakdown. Instant results, no sign-up.',
    category: 'Finance',
    icon: 'lucide:receipt',
    keywords: [
      'gst calculator',
      'gst amount calculator',
      'gst calculator india',
      'gst inclusive calculator',
      'gst exclusive calculator',
      'online gst calculator',
      'gst tax calculator',
      '18 percent gst calculator',
      'gst calculation formula',
      'goods and services tax calculator',
    ],
    relatedTools: ['discount-calculator', 'percentage-calculator', 'emi-calculator', 'sip-calculator'],
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    shortDescription: 'Calculate final price after applying any discount',
    description:
      'Free Discount Calculator to find out how much you save on any purchase. Enter the original price and discount percentage to see the discounted price instantly.',
    seoTitle: 'Discount Calculator — Find Sale Price & Savings Instantly',
    seoDescription:
      'Free Discount Calculator to find the final price after any percentage discount. Enter original price & discount % to instantly see discounted price & exact amount saved.',
    category: 'Finance',
    icon: 'lucide:tag',
    keywords: [
      'discount calculator',
      'price discount calculator',
      'percentage off calculator',
      'sale price calculator',
      'discount percentage calculator',
      'calculate discount online',
      'discount amount calculator',
      'how to calculate discount',
      'original price calculator',
      'percent off calculator',
    ],
    relatedTools: ['gst-calculator', 'percentage-calculator', 'bmi-calculator', 'age-calculator'],
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    shortDescription: 'Calculate exact age in years, months, and days',
    description:
      'Free Age Calculator to find your exact age in years, months, and days from your date of birth. Also shows total days lived and days until your next birthday.',
    seoTitle: 'Age Calculator — Find Exact Age from Date of Birth Online',
    seoDescription:
      'Free Age Calculator to find your exact age in years, months & days from date of birth. Shows total days lived & days until your next birthday. Handles leap years accurately.',
    category: 'Utility',
    icon: 'lucide:calendar-days',
    keywords: [
      'age calculator',
      'age calculator from date of birth',
      'exact age calculator',
      'how old am i calculator',
      'birthday age calculator',
      'age in years months days calculator',
      'age calculation online',
      'date of birth age calculator',
      'age finder online',
      'my age calculator india',
    ],
    relatedTools: ['bmi-calculator', 'percentage-calculator', 'discount-calculator', 'word-counter'],
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'Calculate percentages, percentage change, and more',
    description:
      'Free Percentage Calculator with multiple modes. Find what % of a number is, calculate percentage change, and solve common percentage problems in seconds.',
    seoTitle: 'Percentage Calculator — Calculate % of Any Number Online',
    seoDescription:
      'Free Percentage Calculator with 3 modes: find X% of a number, what % one number is of another, and percentage change. Instant, accurate results online. No sign-up needed.',
    category: 'Utility',
    icon: 'lucide:percent',
    keywords: [
      'percentage calculator',
      'percent calculator online',
      'percentage change calculator',
      'calculate percentage of a number',
      'percentage increase calculator',
      'how to calculate percentage',
      'percentage decrease calculator',
      'marks percentage calculator',
      'percentage difference calculator',
      'percentage formula calculator',
    ],
    relatedTools: ['discount-calculator', 'gst-calculator', 'bmi-calculator', 'sip-calculator'],
  },
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    shortDescription: 'Calculate your Body Mass Index and health category',
    description:
      'Free BMI Calculator to measure your Body Mass Index. Enter your weight and height to instantly know your BMI and whether you are underweight, normal, overweight, or obese.',
    seoTitle: 'BMI Calculator — Check Body Mass Index & Weight Category',
    seoDescription:
      'Free BMI Calculator to find your Body Mass Index instantly. Enter weight & height to check if you are underweight, normal weight, overweight or obese. Includes BMI chart for Indians.',
    category: 'Utility',
    icon: 'lucide:activity',
    keywords: [
      'bmi calculator',
      'body mass index calculator',
      'bmi calculator india',
      'bmi chart',
      'healthy weight calculator',
      'bmi calculator kg cm',
      'ideal weight calculator',
      'obesity calculator',
      'bmi calculator for adults',
      'bmi calculator online free',
    ],
    relatedTools: ['age-calculator', 'percentage-calculator', 'word-counter', 'discount-calculator'],
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    shortDescription: 'Count words, characters, sentences, and reading time',
    description:
      'Free online Word Counter tool. Count words, characters, sentences, paragraphs, and estimate reading time for any text. Perfect for writers, students, and content creators.',
    seoTitle: 'Word Counter — Count Words, Characters & Reading Time Free',
    seoDescription:
      'Free online Word Counter tool. Count words, characters (with & without spaces), sentences, paragraphs & reading time instantly. Works for all languages. 100% private.',
    category: 'Text',
    icon: 'lucide:file-text',
    keywords: [
      'word counter',
      'character counter online',
      'word count tool',
      'online word counter',
      'free word counter',
      'word counter for essay',
      'character count tool',
      'word and character counter',
      'sentence counter online',
      'paragraph counter',
    ],
    relatedTools: ['json-formatter', 'bmi-calculator', 'age-calculator', 'percentage-calculator'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    shortDescription: 'Format, validate, and minify JSON online',
    description:
      'Free online JSON Formatter and Validator. Beautify, format, and minify JSON data instantly. Validate JSON syntax and copy formatted output with one click.',
    seoTitle: 'JSON Formatter — Beautify, Validate & Minify JSON Online',
    seoDescription:
      'Free JSON Formatter to beautify, validate & minify JSON instantly. Paste raw JSON to format with proper indentation & validate syntax. Runs in your browser — data stays private.',
    category: 'Text',
    icon: 'lucide:braces',
    keywords: [
      'json formatter',
      'json beautifier online',
      'json validator',
      'format json online',
      'json pretty print',
      'json minifier online',
      'json formatter online free',
      'json viewer online',
      'json parser online',
      'json formatter and validator',
    ],
    relatedTools: ['word-counter', 'percentage-calculator', 'age-calculator', 'bmi-calculator'],
    fullWidth: true,
  },
  {
    slug: 'hra-calculator',
    name: 'HRA Calculator',
    shortDescription: 'Calculate HRA exemption and taxable HRA amount',
    description: 'Free HRA Calculator to estimate House Rent Allowance tax exemption under old tax regime.',
    seoTitle: 'HRA Calculator - Calculate HRA Exemption Online',
    seoDescription: 'Use this free HRA Calculator to calculate HRA exemption and taxable HRA instantly.',
    category: 'Finance',
    icon: 'lucide:house',
    keywords: ['hra calculator', 'house rent allowance calculator', 'hra exemption calculator', 'tax saving hra'],
    relatedTools: ['gratuity-calculator', 'nps-calculator', 'ppf-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'gratuity-calculator',
    name: 'Gratuity Calculator',
    shortDescription: 'Estimate gratuity amount based on salary and service',
    description: 'Free Gratuity Calculator for private and public employees in India.',
    seoTitle: 'Gratuity Calculator - Calculate Gratuity Amount',
    seoDescription: 'Calculate gratuity amount instantly with salary and years of service.',
    category: 'Finance',
    icon: 'lucide:wallet',
    keywords: ['gratuity calculator', 'gratuity amount calculator', 'salary gratuity'],
    relatedTools: ['hra-calculator', 'nps-calculator', 'ppf-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'nps-calculator',
    name: 'NPS Calculator',
    shortDescription: 'Estimate retirement corpus with NPS contributions',
    description: 'Free NPS Calculator to project National Pension System maturity value.',
    seoTitle: 'NPS Calculator - National Pension System Calculator',
    seoDescription: 'Calculate NPS corpus, lump sum and annuity amount online.',
    category: 'Finance',
    icon: 'lucide:shield',
    keywords: ['nps calculator', 'national pension system calculator', 'retirement calculator nps'],
    relatedTools: ['ppf-calculator', 'gratuity-calculator', 'sip-calculator', 'inflation-calculator'],
  },
  {
    slug: 'ppf-calculator',
    name: 'PPF Calculator',
    shortDescription: 'Calculate PPF maturity amount and interest earned',
    description: 'Free PPF Calculator to estimate Public Provident Fund growth.',
    seoTitle: 'PPF Calculator - Calculate PPF Maturity Online',
    seoDescription: 'Use this PPF Calculator to estimate maturity amount and returns.',
    category: 'Finance',
    icon: 'lucide:piggy-bank',
    keywords: ['ppf calculator', 'public provident fund calculator', 'ppf maturity calculator'],
    relatedTools: ['nps-calculator', 'simple-interest-calculator', 'compound-interest-calculator', 'sip-calculator'],
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    shortDescription: 'Calculate simple interest and final amount quickly',
    description: 'Free simple interest calculator for loans and investments.',
    seoTitle: 'Simple Interest Calculator - SI Calculator Online',
    seoDescription: 'Calculate simple interest instantly with principal, rate and tenure.',
    category: 'Finance',
    icon: 'lucide:calculator',
    keywords: ['simple interest calculator', 'si calculator', 'interest formula calculator'],
    relatedTools: ['compound-interest-calculator', 'ppf-calculator', 'fd-calculator', 'emi-calculator'],
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    shortDescription: 'Calculate compound interest with compounding frequency',
    description: 'Free compound interest calculator for savings and investments.',
    seoTitle: 'Compound Interest Calculator - CI Calculator Online',
    seoDescription: 'Calculate compound interest and maturity amount instantly.',
    category: 'Finance',
    icon: 'lucide:bar-chart-3',
    keywords: ['compound interest calculator', 'ci calculator', 'maturity amount calculator'],
    relatedTools: ['simple-interest-calculator', 'fd-calculator', 'ppf-calculator', 'sip-calculator'],
  },
  {
    slug: 'loan-eligibility-calculator',
    name: 'Loan Eligibility Calculator',
    shortDescription: 'Estimate maximum loan amount based on income and EMIs',
    description: 'Free loan eligibility calculator for home and personal loans.',
    seoTitle: 'Loan Eligibility Calculator - Check Loan Eligibility',
    seoDescription: 'Estimate eligible loan amount instantly using salary and obligations.',
    category: 'Finance',
    icon: 'lucide:badge-dollar-sign',
    keywords: ['loan eligibility calculator', 'home loan eligibility calculator', 'maximum loan calculator'],
    relatedTools: ['emi-calculator', 'credit-card-emi-calculator', 'compound-interest-calculator', 'nps-calculator'],
  },
  {
    slug: 'credit-card-emi-calculator',
    name: 'Credit Card EMI Calculator',
    shortDescription: 'Calculate EMI and interest for credit card purchases',
    description: 'Free credit card EMI calculator with monthly installment breakup.',
    seoTitle: 'Credit Card EMI Calculator - Calculate Monthly EMI',
    seoDescription: 'Calculate credit card EMI, total interest and repayment instantly.',
    category: 'Finance',
    icon: 'lucide:credit-card',
    keywords: ['credit card emi calculator', 'card emi calculator', 'credit card interest calculator'],
    relatedTools: ['emi-calculator', 'loan-eligibility-calculator', 'simple-interest-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    shortDescription: 'See how inflation changes future cost and purchasing power',
    description: 'Free inflation calculator for future value and purchasing power.',
    seoTitle: 'Inflation Calculator - Calculate Future Value',
    seoDescription: 'Calculate inflation impact on your money over time.',
    category: 'Finance',
    icon: 'lucide:trending-up',
    keywords: ['inflation calculator', 'future value calculator', 'purchasing power calculator'],
    relatedTools: ['nps-calculator', 'ppf-calculator', 'sip-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'cm-to-feet-inches-converter',
    name: 'CM to Feet & Inches Converter',
    shortDescription: 'Convert centimeters to feet and inches quickly',
    description: 'Free centimeter to feet-inch converter.',
    seoTitle: 'CM to Feet & Inches Converter - Online Tool',
    seoDescription: 'Convert cm to feet and inches instantly and accurately.',
    category: 'Utility',
    icon: 'lucide:ruler',
    keywords: ['cm to feet', 'cm to feet inches', 'height converter'],
    relatedTools: ['kg-to-pounds-converter', 'celsius-to-fahrenheit-converter', 'miles-to-km-converter', 'seconds-to-hours-converter'],
  },
  {
    slug: 'kg-to-pounds-converter',
    name: 'KG to Pounds Converter',
    shortDescription: 'Convert kilograms to pounds instantly',
    description: 'Free kg to lb converter for weights.',
    seoTitle: 'KG to Pounds Converter - Kg to Lb Online',
    seoDescription: 'Convert kilograms to pounds with accurate conversion.',
    category: 'Utility',
    icon: 'lucide:weight',
    keywords: ['kg to pounds', 'kg to lb converter', 'weight converter'],
    relatedTools: ['cm-to-feet-inches-converter', 'celsius-to-fahrenheit-converter', 'square-feet-to-square-meter', 'miles-to-km-converter'],
  },
  {
    slug: 'celsius-to-fahrenheit-converter',
    name: 'Celsius to Fahrenheit Converter',
    shortDescription: 'Convert temperature from Celsius to Fahrenheit',
    description: 'Free Celsius to Fahrenheit converter.',
    seoTitle: 'Celsius to Fahrenheit Converter - C to F',
    seoDescription: 'Convert Celsius to Fahrenheit instantly with formula output.',
    category: 'Utility',
    icon: 'lucide:thermometer',
    keywords: ['celsius to fahrenheit', 'c to f converter', 'temperature converter'],
    relatedTools: ['kg-to-pounds-converter', 'cm-to-feet-inches-converter', 'seconds-to-hours-converter', 'miles-to-km-converter'],
  },
  {
    slug: 'square-feet-to-square-meter',
    name: 'Square Feet to Square Meter',
    shortDescription: 'Convert area from square feet to square meters',
    description: 'Free sq ft to sq meter converter.',
    seoTitle: 'Square Feet to Square Meter Converter',
    seoDescription: 'Convert square feet to square meters online.',
    category: 'Utility',
    icon: 'lucide:square',
    keywords: ['square feet to square meter', 'sqft to sqm', 'area converter'],
    relatedTools: ['miles-to-km-converter', 'cm-to-feet-inches-converter', 'kg-to-pounds-converter', 'seconds-to-hours-converter'],
  },
  {
    slug: 'miles-to-km-converter',
    name: 'Miles to KM Converter',
    shortDescription: 'Convert miles to kilometers quickly',
    description: 'Free miles to km converter.',
    seoTitle: 'Miles to KM Converter - Mile to Kilometer',
    seoDescription: 'Convert miles to kilometers instantly.',
    category: 'Utility',
    icon: 'lucide:route',
    keywords: ['miles to km', 'mile to kilometer', 'distance converter'],
    relatedTools: ['square-feet-to-square-meter', 'seconds-to-hours-converter', 'cm-to-feet-inches-converter', 'kg-to-pounds-converter'],
  },
  {
    slug: 'seconds-to-hours-converter',
    name: 'Seconds to Hours Converter',
    shortDescription: 'Convert seconds into hours and HH:MM:SS format',
    description: 'Free seconds to hours converter.',
    seoTitle: 'Seconds to Hours Converter - Time Converter',
    seoDescription: 'Convert seconds to hours, minutes and seconds instantly.',
    category: 'Utility',
    icon: 'lucide:timer',
    keywords: ['seconds to hours', 'seconds converter', 'time converter'],
    relatedTools: ['time-duration-calculator', 'countdown-timer-date-based', 'week-number-calculator', 'miles-to-km-converter'],
  },
  {
    slug: 'binary-to-decimal-converter',
    name: 'Binary to Decimal Converter',
    shortDescription: 'Convert binary numbers to decimal values',
    description: 'Free binary to decimal number converter.',
    seoTitle: 'Binary to Decimal Converter - Online Tool',
    seoDescription: 'Convert binary to decimal quickly with instant output.',
    category: 'Text',
    icon: 'lucide:binary',
    keywords: ['binary to decimal', 'binary converter', 'base conversion'],
    relatedTools: ['base64-encoder-decoder', 'number-to-words-converter', 'url-encoder-decoder', 'json-formatter'],
  },
  {
    slug: 'number-to-words-converter',
    name: 'Number to Words Converter',
    shortDescription: 'Convert numbers into readable words',
    description: 'Free number to words converter.',
    seoTitle: 'Number to Words Converter - Online Tool',
    seoDescription: 'Convert numeric values into words instantly.',
    category: 'Text',
    icon: 'lucide:text',
    keywords: ['number to words', 'number in words converter', 'amount in words'],
    relatedTools: ['binary-to-decimal-converter', 'slug-generator', 'text-sorter-az', 'word-counter'],
  },
  {
    slug: 'working-days-calculator',
    name: 'Working Days Calculator',
    shortDescription: 'Count working days between two dates',
    description: 'Free working days calculator excluding weekends.',
    seoTitle: 'Working Days Calculator - Count Workdays',
    seoDescription: 'Calculate working days between two dates instantly.',
    category: 'Utility',
    icon: 'lucide:calendar',
    keywords: ['working days calculator', 'workday calculator', 'business day count'],
    relatedTools: ['business-days-calculator', 'time-duration-calculator', 'week-number-calculator', 'countdown-timer-date-based'],
  },
  {
    slug: 'business-days-calculator',
    name: 'Business Days Calculator',
    shortDescription: 'Calculate business days between start and end dates',
    description: 'Free business days date calculator.',
    seoTitle: 'Business Days Calculator - Date Difference Tool',
    seoDescription: 'Count business days between dates with this free calculator.',
    category: 'Utility',
    icon: 'lucide:briefcase',
    keywords: ['business days calculator', 'working days between dates', 'weekday calculator'],
    relatedTools: ['working-days-calculator', 'time-duration-calculator', 'age-difference-calculator', 'week-number-calculator'],
  },
  {
    slug: 'week-number-calculator',
    name: 'Week Number Calculator',
    shortDescription: 'Find ISO week number for any date',
    description: 'Free week number finder for dates.',
    seoTitle: 'Week Number Calculator - ISO Week Finder',
    seoDescription: 'Find the week number for any date instantly.',
    category: 'Utility',
    icon: 'lucide:calendar-range',
    keywords: ['week number calculator', 'iso week number', 'week finder'],
    relatedTools: ['working-days-calculator', 'business-days-calculator', 'countdown-timer-date-based', 'time-duration-calculator'],
  },
  {
    slug: 'countdown-timer-date-based',
    name: 'Countdown Timer (date-based)',
    shortDescription: 'Calculate days remaining until a target date',
    description: 'Free date based countdown timer.',
    seoTitle: 'Countdown Timer - Date Based Countdown Tool',
    seoDescription: 'Calculate countdown to any date in days.',
    category: 'Utility',
    icon: 'lucide:hourglass',
    keywords: ['countdown timer', 'date countdown', 'days until date'],
    relatedTools: ['time-duration-calculator', 'week-number-calculator', 'working-days-calculator', 'age-difference-calculator'],
  },
  {
    slug: 'age-difference-calculator',
    name: 'Age Difference Calculator',
    shortDescription: 'Calculate exact age gap between two dates',
    description: 'Free age difference calculator online.',
    seoTitle: 'Age Difference Calculator - Date Gap Tool',
    seoDescription: 'Calculate age difference in years, months and days.',
    category: 'Utility',
    icon: 'lucide:users',
    keywords: ['age difference calculator', 'date difference age', 'age gap calculator'],
    relatedTools: ['age-calculator', 'time-duration-calculator', 'working-days-calculator', 'business-days-calculator'],
  },
  {
    slug: 'time-duration-calculator',
    name: 'Time Duration Calculator',
    shortDescription: 'Calculate time duration between two dates',
    description: 'Free time duration and date difference calculator.',
    seoTitle: 'Time Duration Calculator - Date Difference',
    seoDescription: 'Calculate duration between dates in days and hours.',
    category: 'Utility',
    icon: 'lucide:clock-3',
    keywords: ['time duration calculator', 'date duration calculator', 'difference between dates'],
    relatedTools: ['working-days-calculator', 'business-days-calculator', 'countdown-timer-date-based', 'age-difference-calculator'],
  },
  {
    slug: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    shortDescription: 'Clean text by removing extra spaces and gaps',
    description: 'Free text cleaner to remove extra spaces.',
    seoTitle: 'Remove Extra Spaces Tool - Text Cleaner',
    seoDescription: 'Remove extra spaces from text instantly online.',
    category: 'Text',
    icon: 'lucide:eraser',
    keywords: ['remove extra spaces', 'text cleaner', 'space remover'],
    relatedTools: ['text-sorter-az', 'reverse-text-generator', 'slug-generator', 'html-to-text-converter'],
  },
  {
    slug: 'text-sorter-az',
    name: 'Text Sorter (A-Z)',
    shortDescription: 'Sort text lines alphabetically in one click',
    description: 'Free A-Z text sorter online.',
    seoTitle: 'Text Sorter A-Z - Sort Lines Online',
    seoDescription: 'Sort text lines alphabetically from A to Z instantly.',
    category: 'Text',
    icon: 'lucide:arrow-down-a-z',
    keywords: ['text sorter', 'sort text a-z', 'alphabetical order tool'],
    relatedTools: ['remove-extra-spaces', 'reverse-text-generator', 'slug-generator', 'word-counter'],
  },
  {
    slug: 'reverse-text-generator',
    name: 'Reverse Text Generator',
    shortDescription: 'Reverse text characters instantly',
    description: 'Free reverse text generator online.',
    seoTitle: 'Reverse Text Generator - Flip Text Online',
    seoDescription: 'Reverse any text instantly with this free generator.',
    category: 'Text',
    icon: 'lucide:flip-horizontal',
    keywords: ['reverse text generator', 'flip text', 'backward text tool'],
    relatedTools: ['text-sorter-az', 'remove-extra-spaces', 'slug-generator', 'word-counter'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    shortDescription: 'Generate SEO-friendly URL slugs from text',
    description: 'Free SEO slug generator for URLs.',
    seoTitle: 'Slug Generator - SEO Friendly URL Slug Tool',
    seoDescription: 'Generate clean and SEO-friendly slugs for pages and blogs.',
    category: 'Text',
    icon: 'lucide:link-2',
    keywords: ['slug generator', 'seo slug tool', 'url slug generator'],
    relatedTools: ['remove-extra-spaces', 'text-sorter-az', 'url-encoder-decoder', 'word-counter'],
  },
  {
    slug: 'html-to-text-converter',
    name: 'HTML to Text Converter',
    shortDescription: 'Convert HTML markup into plain text output',
    description: 'Free HTML to plain text converter.',
    seoTitle: 'HTML to Text Converter - Strip HTML Tags',
    seoDescription: 'Convert HTML to clean plain text instantly.',
    category: 'Text',
    icon: 'lucide:file-code',
    keywords: ['html to text', 'strip html tags', 'html converter'],
    relatedTools: ['remove-extra-spaces', 'slug-generator', 'url-encoder-decoder', 'json-formatter'],
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    shortDescription: 'Encode and decode URLs safely',
    description: 'Free URL encoder and decoder tool.',
    seoTitle: 'URL Encoder Decoder - Encode Decode URLs',
    seoDescription: 'Encode and decode URL strings instantly.',
    category: 'Text',
    icon: 'lucide:globe',
    keywords: ['url encoder decoder', 'url encode', 'url decode'],
    relatedTools: ['base64-encoder-decoder', 'slug-generator', 'html-to-text-converter', 'json-formatter'],
  },
  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder / Decoder',
    shortDescription: 'Encode and decode Base64 strings',
    description: 'Free Base64 encode decode tool.',
    seoTitle: 'Base64 Encoder Decoder - Online Tool',
    seoDescription: 'Encode text to Base64 and decode Base64 instantly.',
    category: 'Text',
    icon: 'lucide:lock-keyhole',
    keywords: ['base64 encoder decoder', 'base64 encode', 'base64 decode'],
    relatedTools: ['url-encoder-decoder', 'binary-to-decimal-converter', 'json-formatter', 'html-to-text-converter'],
  },
  {
    slug: 'strong-password-generator',
    name: 'Strong Password Generator',
    shortDescription: 'Generate secure strong passwords instantly',
    description: 'Free strong password generator tool.',
    seoTitle: 'Strong Password Generator - Secure Password Tool',
    seoDescription: 'Generate random strong passwords for better security.',
    category: 'Text',
    icon: 'lucide:key-round',
    keywords: ['strong password generator', 'password generator', 'secure password tool'],
    relatedTools: ['random-string-generator', 'uuid-generator', 'base64-encoder-decoder', 'slug-generator'],
  },
  {
    slug: 'random-string-generator',
    name: 'Random String Generator',
    shortDescription: 'Random text with custom length, A–Z, a–z, 0–9, symbols, or hex',
    description:
      'Generate random strings with adjustable length (1–512) and character sets: uppercase, lowercase, numbers, symbols, optional ambiguous-character exclusion, and hexadecimal (0–9, a–f) mode with quick presets.',
    seoTitle: 'Random String Generator — Length, Upper, Lower, Numbers, Symbols, Hex',
    seoDescription:
      'Create random strings online: choose length, include upper/lower case, digits, symbols, exclude ambiguous characters, or generate hex strings. Free browser-based tool for devs and QA.',
    category: 'Text',
    icon: 'lucide:a-large-small',
    keywords: [
      'random string generator',
      'random text generator',
      'alphanumeric string generator',
      'hex string generator',
      'uppercase random string',
      'lowercase random string',
    ],
    relatedTools: ['strong-password-generator', 'uuid-generator', 'base64-encoder-decoder', 'slug-generator'],
  },
  {
    slug: 'random-color-generator',
    name: 'Random Color Generator',
    shortDescription: 'Generate random HEX color codes instantly',
    description: 'Free random color hex generator.',
    seoTitle: 'Random Color Generator - HEX Color Tool',
    seoDescription: 'Generate random hex colors for design and UI work.',
    category: 'Text',
    icon: 'lucide:palette',
    keywords: ['random color generator', 'hex color generator', 'color picker random'],
    relatedTools: ['random-string-generator', 'uuid-generator', 'slug-generator', 'json-formatter'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    shortDescription: 'Generate UUID v4 IDs in one click',
    description: 'Free UUID generator for developers.',
    seoTitle: 'UUID Generator - Generate UUID v4 Online',
    seoDescription: 'Generate random UUID v4 strings instantly online.',
    category: 'Text',
    icon: 'lucide:fingerprint',
    keywords: ['uuid generator', 'uuid v4 generator', 'guid generator'],
    relatedTools: ['random-string-generator', 'strong-password-generator', 'base64-encoder-decoder', 'json-formatter'],
  },
  {
    slug: 'random-date-generator',
    name: 'Random Date Generator',
    shortDescription: 'Generate random dates within a valid range',
    description: 'Free random date generator tool.',
    seoTitle: 'Random Date Generator - Online Tool',
    seoDescription: 'Generate random dates quickly for testing and demos.',
    category: 'Utility',
    icon: 'lucide:calendar-plus',
    keywords: ['random date generator', 'date generator', 'test data date'],
    relatedTools: ['fake-name-generator', 'uuid-generator', 'working-days-calculator', 'time-duration-calculator'],
  },
  {
    slug: 'fake-name-generator',
    name: 'Fake Name Generator',
    shortDescription: 'Generate random fake names for test data',
    description: 'Free fake name generator for sample data.',
    seoTitle: 'Fake Name Generator - Random Test Names',
    seoDescription: 'Generate random fake names instantly for testing.',
    category: 'Utility',
    icon: 'lucide:user-round-plus',
    keywords: ['fake name generator', 'random name generator', 'test data names'],
    relatedTools: ['random-date-generator', 'uuid-generator', 'random-string-generator', 'word-counter'],
  },
  {
    slug: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    shortDescription: 'Focus timer using the Pomodoro productivity method',
    description: 'Free Pomodoro timer for focused work sessions.',
    seoTitle: 'Pomodoro Timer - Free Focus Timer',
    seoDescription: 'Use a simple 25-minute Pomodoro timer to improve focus.',
    category: 'Utility',
    icon: 'lucide:timer-reset',
    keywords: ['pomodoro timer', 'focus timer', '25 minute timer'],
    relatedTools: [
      'fullscreen-stopwatch',
      'fullscreen-countdown-timer',
      'countdown-timer-date-based',
      'time-duration-calculator',
    ],
  },
  {
    slug: 'fullscreen-stopwatch',
    name: 'Fullscreen Stopwatch',
    shortDescription: 'Edge-to-edge stopwatch, big time, custom backgrounds, browser fullscreen',
    description:
      'Immersive fullscreen stopwatch: large center clock, optional pure black or gradient/photo backgrounds, your own image, space to start and pause, and an Enter/Exit fullscreen control for a distraction-free screen.',
    seoTitle: 'Fullscreen Stopwatch — Big Timer, Black or Photo Background, Online',
    seoDescription:
      'Use a free browser fullscreen stopwatch: huge centered digits, true black or scenic backgrounds, upload your own image, one-click full screen, no clutter. Ideal for focus blocks, events, and presentations.',
    category: 'Utility',
    icon: 'lucide:timer',
    keywords: [
      'fullscreen stopwatch',
      'online stopwatch fullscreen',
      'big display stopwatch',
      'dark stopwatch',
      'minimal stopwatch',
      'presentation timer',
    ],
    relatedTools: ['fullscreen-countdown-timer', 'pomodoro-timer', 'time-duration-calculator', 'countdown-timer-date-based'],
    fullWidth: true,
    immersive: true,
  },
  {
    slug: 'fullscreen-countdown-timer',
    name: 'Fullscreen Countdown Timer',
    shortDescription: 'Count down with a clean full-screen view and custom or default backgrounds',
    description:
      'Set hours, minutes, and seconds, then use a full-screen or pure black view with a large countdown, your choice of default photos or solid colors, a custom image, and browser-level fullscreen. Sound cue when time reaches zero (where supported).',
    seoTitle: 'Fullscreen Countdown Timer — Set Duration, Black or Image Background',
    seoDescription:
      'Free online fullscreen countdown: set h/m/s, huge digits, true black, gradients, built-in sample photos, or your own background image, plus enter/exit fullscreen. Browser-based; on-screen display stays minimal; article below explains usage.',
    category: 'Utility',
    icon: 'lucide:hourglass',
    keywords: [
      'fullscreen countdown timer',
      'online countdown fullscreen',
      'big timer countdown',
      'dark countdown',
      'presentation countdown',
    ],
    relatedTools: ['fullscreen-stopwatch', 'pomodoro-timer', 'countdown-timer-date-based', 'time-duration-calculator'],
    fullWidth: true,
    immersive: true,
  },
  {
    slug: 'typing-speed-test',
    name: 'Typing Speed Test',
    shortDescription: 'WPM test with live accuracy, errors, and color-coded keys',
    description:
      'Free online typing speed test with words per minute (WPM), accuracy percentage, and error count. See correct characters in green and mistakes in red. Pick short, medium, long, or code samples—or paste your own text.',
    seoTitle: 'Typing Speed Test (WPM) — Free Online, Accuracy & Color Feedback',
    seoDescription:
      'Measure typing WPM, accuracy, and errors in the browser. Green/red feedback per character, custom passages, and code-style practice. No install; your typing stays on your device.',
    category: 'Utility',
    icon: 'lucide:keyboard',
    keywords: [
      'typing speed test',
      'wpm test',
      'typing test online',
      'words per minute test',
      'typing accuracy test',
      'free wpm test',
      'type test online',
      'keyboard typing test',
    ],
    relatedTools: ['click-speed-test-cps-test', 'pomodoro-timer', 'word-counter', 'text-sorter-az'],
    fullWidth: true,
  },
  {
    slug: 'click-speed-test-cps-test',
    name: 'Click Speed Test (CPS test)',
    shortDescription: 'Test mouse click speed in clicks per second',
    description: 'Free CPS click speed tester.',
    seoTitle: 'Click Speed Test - CPS Test Online',
    seoDescription: 'Measure mouse clicks per second with this CPS test.',
    category: 'Utility',
    icon: 'lucide:mouse-pointer-click',
    keywords: ['click speed test', 'cps test', 'mouse click test'],
    relatedTools: ['typing-speed-test', 'pomodoro-timer', 'screen-resolution-checker', 'time-duration-calculator'],
  },
  {
    slug: 'screen-resolution-checker',
    name: 'Screen Resolution Checker',
    shortDescription: 'Check your screen and viewport resolution instantly',
    description: 'Free screen resolution checker for devices.',
    seoTitle: 'Screen Resolution Checker - Viewport Size Tool',
    seoDescription: 'Check screen resolution, viewport size and DPR online.',
    category: 'Utility',
    icon: 'lucide:monitor-smartphone',
    keywords: ['screen resolution checker', 'viewport checker', 'display resolution tool'],
    relatedTools: ['ip-info-viewer-frontend-fetch', 'click-speed-test-cps-test', 'typing-speed-test', 'random-color-generator'],
  },
  {
    slug: 'ip-info-viewer-frontend-fetch',
    name: 'IP Info Viewer (frontend fetch)',
    shortDescription: 'Fetch and view public IP and geo details',
    description: 'Free IP info viewer with browser fetch.',
    seoTitle: 'IP Info Viewer - Check Public IP Details',
    seoDescription: 'View your public IP address and network information instantly.',
    category: 'Utility',
    icon: 'lucide:network',
    keywords: ['ip info viewer', 'my ip address', 'ip lookup tool'],
    relatedTools: ['screen-resolution-checker', 'url-encoder-decoder', 'base64-encoder-decoder', 'json-formatter'],
  },
  {
    slug: 'old-vs-new-tax-regime-calculator',
    name: 'Old vs New Tax Regime (India)',
    shortDescription: 'Compare estimated tax under old and new income tax regime',
    description: 'Free Indian income tax comparison with estimated deductions, standard deduction, and regime slabs.',
    seoTitle: 'Old vs New Tax Regime Calculator India | Compare Income Tax',
    seoDescription: 'Compare estimated income tax under old regime (with 80C-style deductions) vs new regime. Illustrative only.',
    category: 'Finance',
    icon: 'lucide:scale',
    keywords: ['old vs new tax regime', 'income tax calculator india', 'new tax regime', 'old tax regime'],
    relatedTools: ['take-home-salary-calculator-india', 'hra-calculator', 'nps-calculator', 'epf-calculator'],
  },
  {
    slug: 'take-home-salary-calculator-india',
    name: 'Take Home Salary Calculator (India)',
    shortDescription: 'Annual and monthly in-hand from CTC, bonus, EPF, and tax',
    description: 'Estimate take-home pay after EPF, TDS, and other annual deductions. Free, browser-based.',
    seoTitle: 'Take Home Salary Calculator India | In-Hand CTC to Net',
    seoDescription: 'Calculate monthly and annual in-hand salary from CTC, bonus, EPF, tax TDS, and other deductions in India.',
    category: 'Finance',
    icon: 'lucide:wallet',
    keywords: ['take home salary calculator', 'in hand salary', 'ctc to net', 'india salary calculator'],
    relatedTools: ['old-vs-new-tax-regime-calculator', 'epf-calculator', 'esic-calculator', 'gratuity-calculator'],
  },
  {
    slug: 'epf-calculator',
    name: 'EPF Calculator (India)',
    shortDescription: 'EPF balance estimate with compounding and contributions',
    description: 'Estimate Employees Provident Fund balance using capped wages and compounding. Illustrative.',
    seoTitle: 'EPF Calculator India | EPF Maturity and Interest',
    seoDescription: 'Free EPF balance calculator: basic/Da, years, and interest. Simplified EPF and employer share.',
    category: 'Finance',
    icon: 'lucide:landmark',
    keywords: ['epf calculator', 'epf interest calculator', 'provident fund calculator india'],
    relatedTools: ['nps-calculator', 'ppf-calculator', 'take-home-salary-calculator-india', 'esic-calculator'],
  },
  {
    slug: 'esic-calculator',
    name: 'ESIC Calculator (India)',
    shortDescription: 'Employee & employer ESI on eligible wages with ceiling',
    description: 'Check ESIC contribution when monthly gross is within the wage ceiling. Free tool.',
    seoTitle: 'ESIC Calculator India | ESI Employee Employer Contribution',
    seoDescription: 'Calculate ESIC employee 0.75% and employer 3.25% for gross up to the ceiling. Eligibility check.',
    category: 'Finance',
    icon: 'lucide:heart-pulse',
    keywords: ['esic calculator', 'esi contribution', 'esic rate india'],
    relatedTools: ['epf-calculator', 'take-home-salary-calculator-india', 'gratuity-calculator', 'hra-calculator'],
  },
  {
    slug: 'leave-encashment-calculator',
    name: 'Leave Encashment Calculator (India)',
    shortDescription: 'Encashment amount from basic and leave days (estimate)',
    description: 'Estimate leave encashment as basic divided by 365 times leave days. Rules vary by employer and tax law.',
    seoTitle: 'Leave Encashment Calculator India | Cash for Leave',
    seoDescription: 'Free leave encashment estimate from monthly basic and number of days. Not legal or tax advice.',
    category: 'Finance',
    icon: 'lucide:calendar-x',
    keywords: ['leave encashment calculator', 'encashment amount', 'leave encashment india'],
    relatedTools: ['gratuity-calculator', 'salary-hike-calculator', 'bonus-calculator', 'epf-calculator'],
  },
  {
    slug: 'overtime-pay-calculator',
    name: 'Overtime Pay Calculator',
    shortDescription: 'Overtime pay from hourly rate, hours, and multiplier',
    description: 'Compute overtime wages as hourly rate × hours × multiplier (e.g. 2x).',
    seoTitle: 'Overtime Pay Calculator | Wage and Multiplier',
    seoDescription: 'Simple overtime calculator: hourly pay, extra hours, and overtime rate multiplier.',
    category: 'Finance',
    icon: 'lucide:clock',
    keywords: ['overtime pay calculator', 'overtime wage', '1.5x overtime'],
    relatedTools: ['salary-hike-calculator', 'bonus-calculator', 'take-home-salary-calculator-india', 'gratuity-calculator'],
  },
  {
    slug: 'salary-hike-calculator',
    name: 'Salary Hike Calculator',
    shortDescription: 'New salary and raise from % hike — monthly or yearly',
    description: 'See new compensation after a percent hike, with annual or monthly view.',
    seoTitle: 'Salary Hike Calculator | Raise and New Pay',
    seoDescription: 'Compute new annual or monthly salary and difference from current pay and hike percentage.',
    category: 'Finance',
    icon: 'lucide:trending-up',
    keywords: ['salary hike calculator', 'raise calculator', 'percent hike salary'],
    relatedTools: ['bonus-calculator', 'inflation-calculator', 'overtime-pay-calculator', 'percentage-calculator'],
  },
  {
    slug: 'bonus-calculator',
    name: 'Bonus Calculator',
    shortDescription: 'Bonus and total comp from base salary and bonus %',
    description: 'Calculate annual bonus and total compensation. Free, instant results.',
    seoTitle: 'Bonus Calculator | Performance Bonus and Total Pay',
    seoDescription: 'Find bonus amount and total comp from base salary and bonus percentage.',
    category: 'Finance',
    icon: 'lucide:gift',
    keywords: ['bonus calculator', 'annual bonus', 'incentive pay calculator'],
    relatedTools: ['salary-hike-calculator', 'take-home-salary-calculator-india', 'discount-calculator', 'inflation-calculator'],
  },
  {
    slug: 'rent-vs-buy-calculator',
    name: 'Rent vs Buy Calculator (India)',
    shortDescription: 'Compare long-run cash with EMI vs total rent (illustration)',
    description: 'Rough comparison of total EMI plus down payment vs rent over a horizon. Does not value appreciation.',
    seoTitle: 'Rent vs Buy Home Calculator | EMI vs Rent India',
    seoDescription: 'Simple rent versus buy: loan EMI, down payment, and rent over the same years. Educational only.',
    category: 'Finance',
    icon: 'lucide:home',
    keywords: ['rent vs buy calculator', 'should i buy or rent', 'emi vs rent'],
    relatedTools: ['home-loan-affordability-calculator', 'emi-calculator', 'emi-vs-rent-calculator', 'loan-eligibility-calculator'],
  },
  {
    slug: 'home-loan-affordability-calculator',
    name: 'Home Loan Affordability Calculator',
    shortDescription: 'Max loan from income, rates, and tenure (FOIR-style)',
    description: 'Estimate max affordable EMI and loan using 40% of net income and existing obligations.',
    seoTitle: 'Home Loan Affordability Calculator | Max Eligible Loan',
    seoDescription: 'How much home loan you may afford: net income, other EMIs, interest rate, and tenure to max loan amount.',
    category: 'Finance',
    icon: 'lucide:banknote',
    keywords: ['home loan eligibility', 'affordability calculator', 'max emi for home loan'],
    relatedTools: ['loan-eligibility-calculator', 'rent-vs-buy-calculator', 'emi-calculator', 'credit-card-emi-calculator'],
  },
  {
    slug: 'stamp-duty-calculator',
    name: 'Stamp Duty Calculator (India)',
    shortDescription: 'Approx. stamp and registration for property value and state',
    description: 'Very rough state-wise stamp and registration. Verify with local authority before transaction.',
    seoTitle: 'Stamp Duty Calculator India | Registration Fee Estimate',
    seoDescription: 'Quick stamp duty and registration cost estimate for Indian states. Rates vary; verify locally.',
    category: 'Finance',
    icon: 'lucide:file-signature',
    keywords: ['stamp duty calculator', 'property registration', 'registration fee india'],
    relatedTools: ['rent-vs-buy-calculator', 'home-loan-affordability-calculator', 'paint-cost-calculator', 'emi-calculator'],
  },
  {
    slug: 'paint-cost-calculator',
    name: 'Paint Cost Calculator',
    shortDescription: 'Total cost from area and per-square-foot price',
    description: 'Estimate total painting budget from wall or floor area and all-in cost per unit.',
    seoTitle: 'Paint Cost Calculator | Wall Area to Budget',
    seoDescription: 'Wall area times paint and labour per sq ft for quick renovation estimates.',
    category: 'Utility',
    icon: 'lucide:brush',
    keywords: ['paint cost calculator', 'painting estimate', 'wall paint budget'],
    relatedTools: ['stamp-duty-calculator', 'square-feet-to-square-meter', 'discount-calculator', 'cm-to-feet-inches-converter'],
  },
  {
    slug: 'sip-vs-fd-calculator',
    name: 'SIP vs FD Calculator',
    shortDescription: 'Compare future value of monthly SIP with lump in FD (illustration)',
    description: 'Side-by-side maturity from SIP in mutual funds and comparable lump FD. Not product advice.',
    seoTitle: 'SIP vs FD Calculator | Returns Comparison',
    seoDescription: 'Compare SIP final value vs fixed deposit for similar horizon and your assumed rates.',
    category: 'Finance',
    icon: 'lucide:git-compare',
    keywords: ['sip vs fd', 'fd vs mutual fund', 'returns comparison'],
    relatedTools: ['sip-calculator', 'fd-calculator', 'lump-sum-vs-sip-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'lump-sum-vs-sip-calculator',
    name: 'Lump Sum vs SIP Calculator',
    shortDescription: 'Compare one-time investment to monthly SIP in same return assumption',
    description: 'Future value of lump sum with compounding against SIP over the same years.',
    seoTitle: 'Lump Sum vs SIP Calculator | Which Grows More',
    seoDescription: 'Compare Lumpsum and SIP with same annual return and time horizon. Educational.',
    category: 'Finance',
    icon: 'lucide:split',
    keywords: ['lump sum vs sip', 'one time investment vs sip', 'sip comparison'],
    relatedTools: ['sip-calculator', 'sip-vs-fd-calculator', 'fd-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'emi-vs-rent-calculator',
    name: 'EMI vs Rent Calculator',
    shortDescription: 'Annual cost gap between home EMI and rent',
    description: 'Simple yearly difference: monthly EMI compared to same-period rent. Context only.',
    seoTitle: 'EMI vs Rent Per Year | Housing Cost Compare',
    seoDescription: 'See annual EMI versus annual rent in one number for a quick check.',
    category: 'Finance',
    icon: 'lucide:scale',
    keywords: ['emi vs rent', 'rent or emi', 'home loan vs rent cost'],
    relatedTools: ['rent-vs-buy-calculator', 'emi-calculator', 'home-loan-affordability-calculator', 'sip-vs-fd-calculator'],
  },
  {
    slug: 'marks-percentage-calculator',
    name: 'Marks Percentage Calculator',
    shortDescription: 'Percentage from per-subject or line scores (e.g. 18/20)',
    description: 'Add marks in lines as fractions or numbers to get total and percentage. Free, private.',
    seoTitle: 'Marks Percentage Calculator | Exam Score to %',
    seoDescription: 'Enter marks per line (with optional max per line) to see total, max, and final percentage.',
    category: 'Utility',
    icon: 'lucide:graduation-cap',
    keywords: ['marks percentage calculator', 'board exam percentage', 'grade calculator'],
    relatedTools: ['marks-needed-calculator', 'attendance-calculator', 'percentage-calculator', 'bmi-calculator'],
  },
  {
    slug: 'marks-needed-calculator',
    name: 'Marks Needed Calculator',
    shortDescription: 'Required marks in upcoming exams to hit target %',
    description: 'If you have course max and what you have so far, see whether your target final % is still reachable in remaining paper.',
    seoTitle: 'Marks Needed to Pass or Score Target | Exam Planner',
    seoDescription: 'How many more marks you need in remaining portion to hit your target overall percentage.',
    category: 'Utility',
    icon: 'lucide:target',
    keywords: ['marks needed calculator', 'how many marks to pass', 'target percentage exam'],
    relatedTools: ['marks-percentage-calculator', 'attendance-calculator', 'study-planner', 'percentage-calculator'],
  },
  {
    slug: 'attendance-calculator',
    name: 'Attendance Calculator',
    shortDescription: 'Attendance % and extra classes to reach target % (model)',
    description: 'Current attendance and how many all-attended future classes to reach a target, under a simple model.',
    seoTitle: 'Attendance Percentage & Target | Classes Needed',
    seoDescription: 'Class attendance % and whether you need more sessions to meet your minimum % requirement.',
    category: 'Utility',
    icon: 'lucide:user-check',
    keywords: ['attendance calculator', 'class attendance', 'min attendance'],
    relatedTools: ['marks-needed-calculator', 'study-planner', 'marks-percentage-calculator', 'percentage-calculator'],
  },
  {
    slug: 'study-planner',
    name: 'Study Planner',
    shortDescription: 'Rotate subjects with days left until the exam (even split)',
    description: 'List subjects and days; get a simple rotation and block time estimate as a line plan.',
    seoTitle: 'Study Planner for Exams | Subject Split by Days',
    seoDescription: 'Lightweight exam study planner: names of subjects, exam countdown, and rough daily rotation.',
    category: 'Utility',
    icon: 'lucide:book-open',
    keywords: ['study planner', 'exam study schedule', 'subject rotation'],
    relatedTools: ['attendance-calculator', 'countdown-timer-date-based', 'marks-needed-calculator', 'pomodoro-timer'],
  },
  {
    slug: 'fancy-text-generator',
    name: 'Fancy Text Generator',
    shortDescription: 'Unicode styles: bold, circled, full-width and more',
    description: 'Create styled Unicode for bios and captions. Copy results from the list.',
    seoTitle: 'Fancy Text Generator | Unicode Aesthetic',
    seoDescription: 'Transform plain text into bold mathematical Unicode, circled capitals, and full-width for social posts.',
    category: 'Text',
    icon: 'lucide:sparkles',
    keywords: ['fancy text', 'aesthetic text', 'unicode text generator'],
    relatedTools: ['remove-line-breaks-tool', 'sentence-case-converter', 'slug-generator', 'word-counter'],
  },
  {
    slug: 'text-to-handwriting-generator',
    name: 'Text to Handwriting Generator',
    shortDescription: 'Cursive-style preview on canvas and PNG download',
    description: 'Render text with handwriting-like fonts, redraw, and download PNG. Browser-only.',
    seoTitle: 'Text to Handwriting | Canvas PNG Export',
    seoDescription: 'Type text and get a cursive or script preview on a canvas, then download as an image. Not a trained ML model.',
    category: 'Text',
    icon: 'lucide:pen',
    keywords: ['text to handwriting', 'handwriting image', 'cursive text generator'],
    relatedTools: ['fancy-text-generator', 'remove-line-breaks-tool', 'word-counter', 'lorem-ipsum-generator'],
  },
  {
    slug: 'remove-line-breaks-tool',
    name: 'Remove Line Breaks',
    shortDescription: 'Collapse to single line with single spaces',
    description: 'Strip newlines and extra spaces to one line of text for descriptions or ad copy.',
    seoTitle: 'Remove Line Breaks from Text | Online',
    seoDescription: 'Paste long text; get one line with line breaks and whitespace normalized.',
    category: 'Text',
    icon: 'lucide:wrap-text',
    keywords: ['remove line breaks', 'single line text', 'no line breaks'],
    relatedTools: ['add-line-numbers', 'remove-extra-spaces', 'url-encoder-decoder', 'html-to-text-converter'],
  },
  {
    slug: 'add-line-numbers',
    name: 'Add Line Numbers to Text',
    shortDescription: 'Number each line (1. 2. 3. …) for code or notes',
    description: 'Prefix every line in your paste with an incrementing number for documentation.',
    seoTitle: 'Add Line Numbers to Text | List Numbering',
    seoDescription: 'Number lines of plain text; useful for notes, diffs, and instructions.',
    category: 'Text',
    icon: 'lucide:list-ordered',
    keywords: ['add line numbers', 'numbered lines', 'line number text'],
    relatedTools: ['remove-line-breaks-tool', 'text-sorter-az', 'json-formatter', 'word-counter'],
  },
  {
    slug: 'sentence-case-converter',
    name: 'Sentence Case Converter',
    shortDescription: 'Capitalize first letter after . ! ? for sentence case',
    description: 'Convert messy casing to a readable sentence-style capitalisation.',
    seoTitle: 'Sentence Case Converter | Title and Sentence',
    seoDescription: 'Make text use sentence case: first letter of each sentence after punctuation uppercased.',
    category: 'Text',
    icon: 'lucide:case-sensitive',
    keywords: ['sentence case', 'proper sentence case', 'capitalize first letter'],
    relatedTools: ['remove-extra-spaces', 'slug-generator', 'fancy-text-generator', 'word-counter'],
  },
  {
    slug: 'youtube-title-generator',
    name: 'YouTube Title Ideas Generator',
    shortDescription: 'Several title ideas from a topic for thumbnails and A/B',
    description: 'Generate short template titles from your topic or keyword for YouTube. Edit before publishing.',
    seoTitle: 'YouTube Title Ideas Generator from Topic | Free',
    seoDescription: 'Topic in, multiple suggested video titles in list form for you to tweak. Free online.',
    category: 'Utility',
    icon: 'lucide:tv',
    keywords: ['youtube title generator', 'video title ideas', 'youtube topic'],
    relatedTools: ['youtube-tags-generator', 'slug-generator', 'meta-tag-generator', 'word-counter'],
  },
  {
    slug: 'youtube-tags-generator',
    name: 'YouTube Tags Generator',
    shortDescription: 'Tag line from a topic (comma separated)',
    description: 'Build a first-pass comma-separated tag string from your main keyword. Refine in Studio.',
    seoTitle: 'YouTube Tags Generator from Keyword',
    seoDescription: 'Get a list-style tag string for a topic, plus generic tags to trim or localise. Free, browser only.',
    category: 'Utility',
    icon: 'lucide:tags',
    keywords: ['youtube tags', 'video tags', 'hashtag for youtube'],
    relatedTools: ['youtube-title-generator', 'meta-tag-generator', 'open-graph-preview-tool', 'slug-generator'],
  },
  {
    slug: 'instagram-grid-splitter',
    name: 'Instagram Grid Splitter (3×3)',
    shortDescription: 'Split one image into 9 for Instagram carousels',
    description: 'Upload a square (best) image; we slice it into 3 by 3 boxes for posting order. Download each tile.',
    seoTitle: 'Instagram 3x3 Grid Splitter | 9 Part Image',
    seoDescription: 'Free tool to cut one picture into 9 for Instagram post grid. Works in the browser, private to you.',
    category: 'Utility',
    icon: 'lucide:layout-grid',
    keywords: ['instagram grid', '3x3 image split', 'insta split'],
    relatedTools: ['open-graph-preview-tool', 'youtube-title-generator', 'word-counter', 'json-formatter'],
  },
  {
    slug: 'emoji-picker-tool',
    name: 'Emoji Picker (Quick)',
    shortDescription: 'Copy-paste a quick batch of fun emojis',
    description: 'A tiny curated set of emojis; search field for reference (full search not exhaustive).',
    seoTitle: 'Emoji Picker and Copy | Quick Symbols',
    seoDescription: 'Select from a list of emojis. Copy the row for bios and posts. No server; runs locally.',
    category: 'Utility',
    icon: 'lucide:smile',
    keywords: ['emoji picker', 'copy emoji', 'unicode emoji list'],
    relatedTools: ['fancy-text-generator', 'url-encoder-decoder', 'word-counter', 'slug-generator'],
  },
  {
    slug: 'color-converter-hex-rgb',
    name: 'Color Converter (HEX ↔ RGB)',
    shortDescription: 'Convert #RRGGBB to rgb() and the reverse',
    description: 'Paste HEX or CSS rgb() and get the other format for web and design.',
    seoTitle: 'HEX to RGB and RGB to HEX | Color Converter',
    seoDescription: 'Free colour code converter: hex colour string to three RGB values or rgb() back to #hex.',
    category: 'Text',
    icon: 'lucide:palette',
    keywords: ['hex to rgb', 'rgb to hex', 'color code converter'],
    relatedTools: ['random-color-generator', 'meta-tag-generator', 'html-to-text-converter', 'url-encoder-decoder'],
  },
  {
    slug: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    shortDescription: 'Dummy paragraphs of placeholder Latin text',
    description: 'Generate several paragraphs of Lorem Ipsum for layout and type mockups.',
    seoTitle: 'Lorem Ipsum Generator | Dummy Text',
    seoDescription: 'Set paragraph count; get lorem text for Figma, web mockups, and design proofs.',
    category: 'Text',
    icon: 'lucide:file-text',
    keywords: ['lorem ipsum', 'placeholder text', 'dummy text generator'],
    relatedTools: ['word-counter', 'text-to-handwriting-generator', 'json-formatter', 'html-to-text-converter'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'HTML Meta Tag Generator',
    shortDescription: 'Title, description, and basic robots tag snippet',
    description: 'Paste your title and description; copy a minimal &lt;title&gt; and meta name=description and robots line.',
    seoTitle: 'Meta Tag Generator for Title and Description | HTML',
    seoDescription: 'Generate a simple head snippet with title, meta description, and index,follow. Edit before use.',
    category: 'Text',
    icon: 'lucide:code',
    keywords: ['meta tag generator', 'html meta description', 'seo title tag'],
    relatedTools: ['open-graph-preview-tool', 'url-encoder-decoder', 'slug-generator', 'html-to-text-converter'],
  },
  {
    slug: 'open-graph-preview-tool',
    name: 'Open Graph & Social Tag Helper',
    shortDescription: 'og:title and og:description copy-paste for sharing',
    description: 'Build Open Graph style meta property lines and see title and description in one place.',
    seoTitle: 'Open Graph Tag Generator for Social Previews',
    seoDescription: 'Create og:title and og:description lines for better link previews. Verify with your platform.',
    category: 'Text',
    icon: 'lucide:share-2',
    keywords: ['open graph', 'og tags', 'social preview', 'og:title'],
    relatedTools: ['meta-tag-generator', 'youtube-title-generator', 'url-encoder-decoder', 'slug-generator'],
  },
  ...highTrafficTools,
  ...studentTools,
  ...aiContentTools,
];

export const toolsByCategory = tools.reduce<Record<ToolCategory, ToolConfig[]>>(
  (acc, tool) => {
    acc[tool.category].push(tool);
    return acc;
  },
  { Finance: [], Utility: [], Text: [] }
);

export function getToolBySlug(slug: string): ToolConfig | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getRelatedTools(slug: string): ToolConfig[] {
  const tool = getToolBySlug(slug);
  if (!tool) return [];
  return tool.relatedTools
    .map((s) => getToolBySlug(s))
    .filter((t): t is ToolConfig => t !== undefined)
    .slice(0, 5);
}
